### ISSUE TITLE
Available Balance

### ISSUE THREAD

**Issue by samuelbohler** [bitpay/copay#2946] opened 2015-07-01 15:22 UTC
Currently, the wallet balance displays the sum of both confirmed and unconfirmed amounts.
On the Send page, the available balance is the same.

Unconfirmed amounts are not available, and so the number provided might not be helpful for someone trying to use it in order to figure out how much they can send.

Most banking applications make a distinction between an "Accounting Balance" and an "Available Balance".  The former would be the equivalent of showing the sum of confirmed and unconfirmed, the latter would the the equivalent of only showing confirmed.

It would be nice to have these two balances listed and the actual available balance (confirmed balance) on the send page.

**Comment by koalalorenzo** [comment] 2015-07-14 05:46
I think this is important also because of the recent problem with the double spending (and I don't think that is really affecting balances right now). The big problem is that if I make two transaction and one is not confirmed because of a problem, I should not be able to use those funds from my wallet. 

Probably there is a reason (UX) why the authors didn't implement this at the very beginning and decided to go with "one single amount"... but I would love to have an option that will allow me to show unconfirmed balance too, or include it as it is right now.

**Comment by isocolsky** [comment] 2015-07-14 14:19
Actually, unconfirmed transactions _can_ be used as inputs for new transactions and Copay allows this by default. That being said, there are future plans for allowing users to configure the minimum nb of confirmations to consider as valid inputs. I think some distinction will have to be made then between total funds and available funds.

**Comment by sambohler** [comment] 2015-07-14 15:07
+1 @isocolsky

**Comment by matiu** [comment] 2015-08-24 13:14
fixed on v1.1.3

**Closed** 2015-08-24 13:14 UTC
