### ISSUE TITLE
[RESOLVED PARTLY] - Dangerous bug with non-confirmed TXs - incorrect balance!

### ISSUE THREAD

**Issue by Perlover** [bitpay/copay#6056] opened 2017-05-17 08:10 UTC
I found very dangerous bug
I think when i send bitcoins the cange addresses are generated not corrected!
I deleted / restored the wallet but i didn't get bitcoins from change address.
More details are later

**Comment by Isabella417** [comment] 2017-05-17 08:19
Transferred funds to cover pay wallet. Transaction showed up as confirmed. Then in about 30 mins to an hour suddenly disappeared and bal was reading as $0. Trusting that you guys will get this issue resolved soon and funds will be back into the account.

**Comment by Isabella417** [comment] 2017-05-17 08:21
Transferred funds to copay wallet. Transaction showed up as confirmed. Then in about 30 mins to an hour suddenly disappeared and bal was reading as $0. Trusting that you guys will get this issue resolved soon and funds will be back into the account.

**Comment by Perlover** [comment] 2017-05-17 08:28
Here strange balance

https://www.dropbox.com/s/1nmfr1g4womm8wf/media-20170517.png?dl=0

When i saw transaction in blockchain (72854 bits "in" and 8256 "out")
72854 IN:
https://insight.bitpay.com/tx/a29eb4cac64c92eca0092dba4c1b6ed99ac2bcb4a7715e90a22fd0e3928a40da

There is the address 1FKunowFvf1YJjEgnYjtP7mWdAFRqTG1JE is my one

Then i sent 8256 OUT:
https://insight.bitpay.com/tx/bde2094c8b5eec35607ec8c37a88cd79d3367101ea04120e4d2631c093d55979

There the change address 1CggwKhXnomix49S1gjHWfB9RBrNhc2JUf should me my one but i don't see this address in list of wallet addresses in Copay application

When i deleted the cache - no changes...
I did "Delete wallet" and restored from xpriv key
After i didn't see any changes! No 0.06423368 BTC from change address in balance!

I don't know is it bug or not. May be v3.2.0 is hacked and change addressses are not my ones? Or lag servers...

I am ready to suggest XPRIV key for developers for testing but i don't know contacts (the user cmgustavo doesn't have email only blog without contacts)

**Comment by Perlover** [comment] 2017-05-17 08:33
I tried to restore wallet in Mycelium but Mycelium doesn't understand XPRIV key - it says "I understand only Level 3 private keys, your XPRIV is zero level"
So i find ways to restore wallet in other applications to see change addresses

**Comment by Perlover** [comment] 2017-05-17 09:02
I resolved this problem!
I used the site for getting BIP44 key for importing to Mycelium
https://iancoleman.github.io/bip39/
When i imported i saw the not-confirmed transaction:
https://blockchain.info/tx/a8522cba49a014497e9a1c3d0e4100d988410b1b6bbca74807dcc10d967f49db
It uses the bitcoins from address 1CggwKhXnomix49S1gjHWfB9RBrNhc2JUf
I used it yesterday but i forgot about this. But! The Copay didn't show to me this transaction and didn't see this transaction completely so it shows to me incorrect balance.
The incorrect balance there is because the Copay didn't take in account the change address 1LVd92meNki2UiaAyL8oseJJwTYnDYuoq but it takes in account used input of transaction a8522cba49a014497e9a1c3d0e4100d988410b1b6bbca74807dcc10d967f49db. So it takes in account the last not-confirmed transactino as partly so balance is not correct...
It should be patched and i think it's serious bug but not dangerous for users. And a restoring wallet or deletion of cache will not help to see correct balance...

**Comment by Perlover** [comment] 2017-05-17 09:22
Wfter importing BIP44 key from Copay to Mycelium i did CPFP transaction from Mycelium (Child pays for parent)
So i think soon i will see correct balance.
I recommend to other users who have same problems to do same through https://iancoleman.github.io/bip39/ if you need to quickly use your coins or wait...

**Comment by Perlover** [comment] 2017-05-17 11:32
Even when my unconfirmed transaction got 2-3 confirmations - i cannot see correct balance
I did restore wallet, clean cache - no results...
Only one way - i sent all bitcoins from restored account of Copay in Mycelium to my other bitcoin wallets.
So goodbye Copay! :(

**Comment by matiu** [comment] 2017-05-17 11:41
Your OP is misleading, there is no indication Copay is generating wrong or 'hacked' address. The fact you were able to recover your funds with the seed alone is a proof of that.  

In the last 24 hours the bitcoin network was very congested and fees keep going up, so TX had a lot of problems to get confirmed and many of then where dropped from the pool.

Closing the issue since you mention you fix it be importing the fee on mycelium.

**Closed by matiu** 2017-05-17 11:41 UTC

**Comment by Perlover** [comment] 2017-05-17 16:24
I fixed it by other bitcoin wallet.
You answer is very strong.
You don't see the problem with Copay. Bitcoin network network is to blame for everything and i too.
Fine...
As you want :)

**Comment by Perlover** [comment] 2017-05-17 16:32
If you will read this issue you will see that balances should be incorrect when the mempool of bitcoin network is big. If your server see an unconfirmed transaction it should take in account or not completly.
I saw other situation: your server doesn't show and "doesn't see" an unconfirmed transaction but in balance outputs of this transaction is deducted!
