### ISSUE TITLE
BTC sent but not receive Coinbase wallet no TXID show in Blockchain

### ISSUE THREAD

**Issue by akashad** [bitpay/copay#7875] opened 2018-01-17 18:15 UTC
My payment sent to faucethub but not receive my coinbase wallet and no txid show in blockchain and no show unconfirmed transaction id in blockchain guys.. please help 
this problem solve any idea here..?? guys 
please help me.. !!

**Comment by justship00** [comment] 2018-01-17 23:37
Same thing I put 50 and I have nonthing 🤧

**Comment by matt77unltd** [comment] 2018-01-19 13:50
Same thing here, mine has been up to a a month nw. I was formally seeing it on blockchain as unconfirmed but now I can no longer see it anymore. God will help us

**Comment by Roddy1219** [comment] 2018-01-22 09:31
@matt77unltd  call me，You can use another wallet ,import your key!

**Comment by BGalliotti** [comment] 2018-05-10 14:37
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will happy to help you.
Thanks

**Closed by BGalliotti** 2018-05-10 14:37 UTC
