### ISSUE TITLE
[iOS - 1.0.0] Too long sentences.

### ISSUE THREAD

**Issue by Kirvx** [bitpay/copay#2809] opened 2015-06-01 22:40 UTC
![img_0001](https://cloud.githubusercontent.com/assets/6627786/7924907/985e3462-08bf-11e5-9f14-c116c9d40ca6.PNG)

Also not that "Add Wallet" is still in English (same for Android).

**Comment by dabura667** [comment] 2015-06-02 03:11
I can confirm "Add Wallet" is still in English for Japanese as well. On both platforms.
As far as spacing is concerned, I plan on running through the app and dealing with those by shortening translations etc.

(I know the first one's obvious, but I thought I'd add my confirmation of the issue)

**Comment by dabura667** [comment] 2015-06-02 03:14
https://github.com/bitpay/copay/blob/master/public/views/add.html#L4

Found the culprit.

Can we add this to the templates.pot file manually? Or will grunt not find it to replace unless grunt found it to parse the template to begin with?

**Comment by cmgustavo** [comment] 2015-06-02 13:30
There was an error in "Add Wallet". "W" should be in lowercase. That 's the reason it wasn't translated. (fixed on #2811)

You can't add string to templates.pot manually, because it will be overwritten by the command "grunt translate".

Regarding this issue (too long strings), I agree that the list is too long for another languages. I think we are repeating "wallet" many times.

**Comment by Kirvx** [comment] 2015-06-02 13:49
I can change 
"Importer un nouveau portefeuille" -> "En créer un nouveau" 
"Rejoindre un portefeuille partagé" -> "En rejoindre un"
"Importer un portefeuille" -> "En importer un"

But "Add wallet" in template.po represents the title and the too long string so maybe add 2 "Add wallet" in template.po for that.

**Comment by Kirvx** [comment] 2015-06-02 14:45
Heu sorry I confused add wirh create

**Closed** 2015-06-02 14:47 UTC
Labels: in progress
