### ISSUE TITLE
Wallet balance not updated despite confirmed transactions

### ISSUE THREAD

**Issue by quinncomendant** [bitpay/copay#4784] opened 2016-10-02 18:30 UTC
I've begun using Copay with only three test transactions:

1. received 1,000 bits (290 confirmations)
2. received 37,144 bits (274 confirmations)
3. sent 1,000 bits (0 confirmations; I just sent it)

Now my wallace balance says **1,000 bits*** and **Pending Confirmation: 35,991 bits**. However, the 37,144 bits were [confirmed 2 days ago](https://blockchain.info/tx/a6dcb1bffbd10b6693b04517e606c50b8768151b7f8a26efe57f449d6e122bd1). Should my wallet include this transaction in its total balance?

Here's the screenshot of the current wallet balance:

![2016-10-02-1](https://cloud.githubusercontent.com/assets/6884276/19022712/107c435c-88a4-11e6-82a7-81f2118204e0.png)

And the detail of transaction a6dcb1bffbd10b6693b04517e606c50b8768151b7f8a26efe57f449d6e122bd1:

![2016-10-02](https://cloud.githubusercontent.com/assets/6884276/19022717/25da739a-88a4-11e6-9e66-3606abd45f7e.png)

I saw this problem previously on a friends device too, but didn't take screenshots. Is this normal behavior? Why is the balance not updated yet?

**Comment by dabura667** [comment] 2016-10-02 22:59
The change is waiting for confirmation.

**Comment by quinncomendant** [comment] 2016-10-03 06:01
@dabura667 But the transaction is confirmed. See [here](https://blockchain.info/tx/a6dcb1bffbd10b6693b04517e606c50b8768151b7f8a26efe57f449d6e122bd1).

**Comment by isocolsky** [comment] 2016-10-03 14:20
Funds in bitcoin are spent in chunks. These chunks correspond to the transactions you received but not yet spent. So if you receive a tx for 1 BTC and you want to send 0.8 BTC to someone else, you will be using that 1 BTC transaction as the input. Since partially spending is not possible you will need to specify where to receive the remaining 0.2 BTC (minus fees). So after the new transaction has been broadcasted you will become the recipient of your own transaction which will be interpreted by the wallet as you having a 0.2 BTC balance. Copay handles all this for you using what is called a change address.
In your case, the change amount will be pending confirmation until the last transaction has one confirmation.
This article explains this in more depth http://www.coindesk.com/information/how-do-bitcoin-transactions-work/

**Comment by quinncomendant** [comment] 2016-10-03 18:29
Ok, that makes sense. Thank you, @isocolsky, for the clear explanation. 

Since Copay manages this "change address," it could make the status of this process available in the UI, so that it might be more clear to the user. Perhaps tapping the "Pending Confirmation" on the main wallet display can toggle the list of all pending transactions to include the change address along with the primary transactions.

**Comment by isocolsky** [comment] 2016-10-04 00:12
Yes definitely. A help sign right next to the pending amount could bring up a message explaining this for people who are new to Bitcoin.

**Closed** 2016-10-14 12:06 UTC

**Comment by dabura667** [comment] 2016-10-14 18:36
Come to think of it, if I forget everything I know of how bitcoin works, this UI is amazingly terrifying.

"I will send $5."

App> "Pending confirmation: $6789"

"Wait... did I just send $6789?"

Copay only shows "Pending confirmation" for balances that are waiting for confirmation, which means only incoming transactions. (If I could make a transaction that only had one output and one input, giving the rest for fee. It would not show up in Copay as "Pending Confirmation")

However, a user would probably think in this situation it means "Pending outgoing transaction" and think that means they are SENDING that amount. It is very confusing.

Perhaps it would be better to have:

# 36,991 bits
#### Immediately available: 1,000 bits

Just having the large number always reflect what a normal user would expect their balance to be will cover 99% of user worries, as 99% of the time, a user isn't sending transactions frequently.

However, in the "Send" window, it should show the "Immediately Available" amount if spending unconfirmed is disabled, and the whole amount if enabled.

**Comment by isocolsky** [comment] 2016-10-15 13:26
I agree with @dabura667 . This is confusing for new users. But I think the best solution is treating change as safe to spend. Since Copay is making the transaction we can assume it will confirm eventually. So the "spend unconfirmed" will only apply to external incoming txs which to me makes sense.

**Comment by investyaakov** [comment] 2017-12-31 15:53
hello,
maybe someone here can help me please,
i have wallet in "cryptonator" and i sent 0.01327908 BTC from my wallet in mycelium to cryptonator (to buy XRP) 
I HAVE RECIVED 58 CONFORMATION and since then i see the bitcoin in pending status
![default](https://user-images.githubusercontent.com/34985880/34462740-297e63b0-ee53-11e7-96c9-1d44ecb66769.PNG)
when i check in blockchain it seems that it past but still have no answer from the soppurt in cryptonator
![2](https://user-images.githubusercontent.com/34985880/34462749-55a607cc-ee53-11e7-835f-bbb05a4d5ac2.PNG)

can someone help please?

this is the idtext
f938d8a4da2352af256cdf2c727477e056a9fc7a7710f81ebe32ee08a54ddae0

Thanks for the help
Matan

**Comment by dabura667** [comment] 2017-12-31 16:13
Contact support of cryptonator.

They sound like a scam.

This has nothing to do with Copay. Please do not post in random githubs with unrelated issues.

Happy New Year.
