### ISSUE TITLE
Pay for invoice - Failed to verify payment protocol signatures

### ISSUE THREAD

**Issue by bogdanN** [bitpay/copay#7676] opened 2017-12-26 16:25 UTC
I've tried to test making payment via "invoice" ability: 
1. Create and redirect user to invoice page:
![2017-12-26 18-19-38](https://user-images.githubusercontent.com/575857/34360438-82129002-ea69-11e7-981b-c269da85d915.png)
2. Copy bitcoin address and paste it into the wallet app and get an error:
![2017-12-26 18-21-58](https://user-images.githubusercontent.com/575857/34360457-c1509624-ea69-11e7-9cf5-53dd9ad642f2.png)
Also I can see the same error  in the log of wallet app:
![2017-12-26 18-24-43](https://user-images.githubusercontent.com/575857/34360503-1d5ffb76-ea6a-11e7-8507-235c4dfa2607.png)
Could anyone help me? What is wrong in the address of payment?

**Comment by cmgustavo** [comment] 2017-12-26 16:52
It 's not an address issue, it fails for verify paypro because you are using testnet (test.bitpay.com)

**Comment by bogdanN** [comment] 2017-12-26 16:56
It has worked ok on Friday morning.

**Comment by cmgustavo** [comment] 2017-12-26 17:20
Because on Friday it has been implemented as Non-backwards-compatible BIP72 payment protocol:

Right now (non-backwards-compatible): bitcoin:?r=xxx
Before (backwards-compatible): bitcoin:<address>?amount=<amount>&r=xxx

**Comment by painchaudAlexandre** [comment] 2017-12-26 17:35
@cmgustavo Hi, do you  know when it will be fixed ?

**Comment by bogdanN** [comment] 2017-12-26 20:14
@cmgustavo, Thank you a lot for clarification.
As I understand we should wait until the BitPay client will be updated? Or we can use "backwards-compatible" links to process payments?

**Comment by sko22** [comment] 2018-01-03 16:34
i'm the same error also.  when it will be fixed ?

**Comment by Keensyst** [comment] 2018-01-03 16:46
I will be honest with y'all, I don't know shit about a computer. I'm 44 yrs old and in the past two years have I layed hands on one

**Comment by lahiruyapa** [comment] 2018-01-05 04:12
Does BitPay Testnet wallet support Bitcoin Payment Protocol?

**Comment by szuranski** [comment] 2018-01-05 05:13
It did until 12/29/2017. After that it no longer worked.

**Comment by Ersian** [comment] 2018-01-08 09:18
Any clue if it will be updated ?

**Comment by prascho** [comment] 2018-01-17 21:03
It was fixed a week ago

**Comment by szuranski** [comment] 2018-01-18 16:13
I can confirm this is working. I can pay an invoice created using Testnet and the payment gets confirmed.

I am not receiving the IPN now though like I was before the issue started happening.

**Closed** 2018-01-18 16:15 UTC

**Comment by prascho** [comment] 2018-01-18 18:02
The IPN stopped working about two days ago - I tested on 15th and it was ok. I am no receiving them at the moment - waiting for recovery.

**Comment by prascho** [comment] 2018-01-22 23:55
The IPN is back online. There is a new issue with test.bitpay.com from the last hour:

> There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team. Please include the Ray ID (which is at the bottom of this error page). Additional troubleshooting resources.

**Comment by mrviit** [comment] 2018-01-24 10:09
I installed CoPay/BitPay on my PC. I'm testing a payment system based on BIP70. I created a link like that "<a href="bitcoin:?r=http://localhost:37391/">Pay</a>" . When I click on the link, the wallet launched then send a http request to my server at http://localhost:37391/. The server returns a PaymentRequest. Like this (I'm using NBitcoin): 
```
public class PaymentServer : IDisposable
    {
        HttpListener _Listener;
        Random rand = new Random();
        string _Prefix;
        public PaymentServer()
        {
            while (true)
            {
                try
                {
                    _Prefix = "http://localhost:37391" /*+ rand.Next(2000, 50000)*/ + "/";
                    _Listener = new HttpListener();
                    _Listener.Prefixes.Add(_Prefix);
                    _Listener.Start();
                    _Listener.BeginGetContext(ListenerCallback, null);
                    break;
                }
                catch (HttpListenerException)
                {
                }
            }
        }

        void ListenerCallback(IAsyncResult ar)
        {
            try
            {
                var context = _Listener.EndGetContext(ar);
                //var type = context.Request.QueryString.Get("type");
                var businessId = 0;// int.Parse(context.Request.QueryString.Get("id"));
                var now = DateTimeOffset.UtcNow;
                var expire = now + TimeSpan.FromDays(1);
                TxOut txOut = new TxOut(Money.Satoshis(1), new Key().ScriptPubKey);
                context.Response.ContentType = PaymentRequest.MediaType;
                PaymentRequest request = new PaymentRequest();
                //request.Details.MerchantData = BitConverter.GetBytes(businessId);
                request.Details.Network = Network.TestNet;
                request.Details.Expires = expire;
                request.Details.Time = now;
                request.Details.PaymentUrl = new Uri(_Prefix + "?id=" + businessId + "&type=Payment");
                request.Details.Outputs.Add(new PaymentOutput(txOut));
                request.WriteTo(context.Response.OutputStream);
                context.Response.Close();
                _Listener.BeginGetContext(ListenerCallback, null);
            }
            catch (Exception)
            {
                if (!_Stopped)
                    throw;
            }
        }
```
But CoPay reported error: "Payment Protocol Invalid". I don't know which was wrong here. This is my side or CoPay. Can/how I investigate CoPay log or source to find the root cause and solution? Thank you very much!

**Comment by mrviit** [comment] 2018-01-24 10:59
This is because of this code src/js/services/payproService.js:
```
else if (!paypro.verified) {
   $log.warn('Failed to verify payment protocol signatures');
   return cb(gettextCatalog.getString('Payment Protocol Invalid'));
}
```

It seems that I have signed the message with wrong PKI key. How can I get a valid key then sign the transaction correctly?
