### ISSUE TITLE
transaction not shown

### ISSUE THREAD

**Issue by wintergarten** [bitpay/copay#8225] opened 2018-03-10 14:25 UTC
I have to ask why my transactions not showing up.
On my other account it is shown that the transaction was successful but I don´t see it or I can´t take it.

Please for a respond

**Comment by wintergarten** [comment] 2018-04-01 16:40
Dear Masclef,

my wallet-ID is: 6580d186-ea0b-4dfc-8f06-cb3cd1c7f2e9,
if you can check it, that would be nice.

If you need further informations, you can contact me.

Kindley regards



2018-03-29 22:38 GMT+02:00 Gabriel Masclef <notifications@github.com>:

**Comment by Gamboster** [comment] 2018-04-09 19:03
Thanks for the wallet id.

I would need a more detailed explanation of what the problem is. Also, some photo showing me the error would also be useful. Send me this info so I can help you. Regards!

**Comment by BGalliotti** [comment] 2018-06-11 18:10
Hello,
We are re-organizing all the support tickets.
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will be happy to help you.
Thanks

**Closed by BGalliotti** 2018-06-11 18:10 UTC
Labels: Pending user response
