### ISSUE TITLE
Key derivation not working since update (also UI scaled down too much)

### ISSUE THREAD

**Issue by Tisbox** [bitpay/copay#4444] opened 2016-06-17 12:48 UTC
Just today I noticed my Copay wallet shows a warning after starting (Copay v2.0.1 on a Windows 8 Phone):
_"WARNING: Key derivation is not working on this device/wallet. Actions cannot be performed on this wallet."_
Well that sounds just awesome considering there's still bitcoins on it :)  Also: it could still receive bitcoins after it started showing the warning.
Copay has worked just fine before, last successful send was 4 days ago. I restarted the phone to no avail.

**Comment by matiu** [comment] 2016-06-17 12:51
Could you try the following:

1) import your wallet (using the backup phrase) on other device (like a PC) and try sending bitcoins from there.
2) create a new wallet on the WP8 device and see if the problem remains.

thanks.

**Comment by Tisbox** [comment] 2016-06-17 12:53
Matiu, you're fast!
Sure I could do that (have done so before using Electrum when I switched phones), but I'm curious as to what's wrong here. Not sure if there's an easy way to find out though...

**Comment by matiu** [comment] 2016-06-17 13:00
Now Copay does 2 checks when creating / importing / reading wallets:

 - Tests HD key derivation by running some hardcoded tests
 - Tests signing and verifying a bitcoin message using your wallet keys

if any of this test fails, the message you see is shown.

If could be a problem with the device/os or... since the test is new, it could just be a bug on our code.

Thats way I asked for that two steps, so we can get more info.

thanks!

**Comment by Tisbox** [comment] 2016-06-17 13:08
I'll import the wallet to Electrum, remove Copay from the phone, install it again and create a new wallet and let you know the results of course (within a few hours).
By the way I've got a vanity set (key pair) that I'd like to use as my Copay wallet, is is possible to create a wallet from the key pair?

**Comment by dabura667** [comment] 2016-06-17 13:18
> I'll import the wallet to Electrum

This won't work. Electrum and Copay are not compatible.

**Comment by matiu** [comment] 2016-06-17 13:55
Yes, but test 1) I meant to import you wallet on other device with Copay (it can be a desktop, for example).

**Comment by Tisbox** [comment] 2016-06-17 14:51
@dabura667: yes it is; Electrum will recover the wallet if you create it as a Trezor hardware wallet, I've successfully done so recently. I've got instructions if you like them, but you can just google it as well.
@matiu: got it, I will try this.

**Comment by Tisbox** [comment] 2016-06-17 18:03
@matiu: I exported the wallet from the phone (text back-up) and imported that in Copay v2.02 on Windows 10. On the PC there's NO mention of key derivation not working. Also I could send bitcoins just fine.
BTW strictly speaking if I had used the backup phrase I'd just have recreated the key pair. By exporting and importing I suppose you could say the problem exists in Copay for Windows phone, correct?

**Comment by Tisbox** [comment] 2016-06-17 18:04
@dabura667: Electrum accepts some seeds not native to Electrum, if you tell it you are restoring a hardware wallet:

- File => New/Restore =>
- enter a wallet name => OK =>
- select Restore a wallet or import keys =>
- select Hardware wallet => Next =>
- select Restore Electrum wallet from device seed words =>
- select TREZOR wallet => Next

**Comment by matiu** [comment] 2016-06-17 18:38
yes. Your statement is exactly right given that the test run OK on WPA and
no other issue make it fail.

It is important that you wallet and funds are OK.

could you try to create a new wallet on WP?

**Comment by Tisbox** [comment] 2016-06-17 22:01
Oh the funds are OK, I'm not worried about those as long as I have the backup phrase. Ironically the funds aren't in the wallet after all :)

I've just created a new wallet on the phone, and that one is validating just fine.
I put 1000 bits on it, and sent those back as well. That too worked just fine (fun exercise with current fees btw, but it's for a good cause).
Also I selected 'receive' on the original wallet, but then get the error: "Could not create address. Cannot create new adress for this wallet".
Do you have any idea what could cause these problems?

So I suppose I best empty and delete the problematic wallet at this point. Which brings me back to my earlier question: I've got a vanity set (key pair) that I'd like to use as my Copay wallet, is is possible to create a wallet from the key pair?

**Comment by RobinTick** [comment] 2016-06-18 12:12
I'm having the same issue on a Lumia 950XL running non-preview Windows 10 mobile.
"WARNING: Key derivation is not working on this device/wallet. Actions cannot be performed on this wallet."

It started because of a Copay app update, I can tell it updated because the UI is now scaled way down and the startup looks different.

There was an OS update a few days earlier but after that the Copay app was working fine.
It's after this app update that the problem occurs.

**Comment by Tisbox** [comment] 2016-06-18 12:25
@RobinTick: that's what I noticed too, the UI being scaled down a lot (way too much imo).

**Comment by LennonRuggier** [comment] 2016-06-19 02:15
Experiencing the same issue here on a Nokia Lumia 930 running Windows phone 10. 
"WARNING: Key derivation is not working on this device/wallet. Actions cannot be performed on this wallet." The UI now scaled way down and there is a looping message "Validating wallet integrity..."

The developers broke the app with the update as it was working flawlessly up to a few days ago.

Are the developers going to fix this bug or are Windows phone users being left out in the cold? You can't reasonably expect everyone to export their wallets, uninstall the app, reinstall the app then import the wallet again.

**Comment by matiu** [comment] 2016-06-19 13:23
> I've got a vanity set (key pair) that I'd like to use as my Copay wallet,
is is possible to create a wallet from the key pair?

you can use a extended private key (see BIP32). to do so, go to create new
wallet an in advanced setting choose "specify seed/phrase' then in the
'recovery phrase' input you can enter a BIP39 mnemonic or an extended
private key in the 'xprix*' format.

thanks for your follow up.

given that you did not erased yet the wallet that throws the error, could
you share the session log with us? you can find it at  Global Settings,
advanced>about copay.  please send it to. matias@bitpay.com

thanks.
On Jun 18, 2016 23:15, "LennonRuggier" <notifications@github.com> wrote:

Experiencing the same issue here on a Nokia Lumia 930 running Windows phone
10.
"WARNING: Key derivation is not working on this device/wallet. Actions
cannot be performed on this wallet." The UI now scaled way down and there
is a looping message "Validating wallet integrity..."

The developers broke the app with the update as it was working flawlessly
up to a few days ago.

Are the developers going to fix this bug or are Windows phone users being
left out in the cold? You can't reasonably expect everyone to export their
wallets, uninstall the app, reinstall the app then import the wallet again.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/4444#issuecomment-226975377>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAGCHHd9Di0jLzbtyn6WSZxnW4eqKGNZks5qNKY0gaJpZM4I4U2f>
.

**Comment by Tisbox** [comment] 2016-06-19 13:35
@matiu: thanks for the vanity set info, I'm sure I can figure that out now.

I'll send you the session log in a minute.

BTW was the new UI really meant to become this small? Because honestly I have to tap the cog icon etc. about 5 times before I finally 'hit' it. Loved the old UI.

**Comment by matiu** [comment] 2016-06-19 13:44
> BTW was the new UI really meant to become this small? Because honestly I
have to tap the cog icon etc. about 5 times before I finally 'hit' it.
Loved the old UI.

not at all. I must be an issue related to WP10 and Ionic. We will try to
reproduce it next week.

@matiu <https://github.com/matiu>: thanks for the vanity set info, I'm sure
I can figure that out now.

I'll send you the session log in a minute.

BTW was the new UI really meant to become this small? Because honestly I
have to tap the cog icon etc. about 5 times before I finally 'hit' it.
Loved the old UI.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/copay/issues/4444#issuecomment-226997653>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAGCHEwRbcoKwduBgNaw9WXYhpXptgFoks5qNUWTgaJpZM4I4U2f>
.

**Comment by RobinTick** [comment] 2016-06-19 15:26
Deleting and reimporting the wallet fixed the problem for my Lumia 950XL W10M.
I don't however this is something a user should have to do after an app update.

**Comment by matiu** [comment] 2016-06-25 18:28
@Tisbox @RobinTick   To understand better the issue, did you happen to have set a 'spending password' set on your wallets at the moment the 'Key verification failed' appear?  What version of Copay were you using?

thanks!

**Comment by Tisbox** [comment] 2016-06-25 20:02
@matiu: yes I had a spending password ever since I started using Copay. Version was/is v2.0.1.

**Comment by matiu** [comment] 2016-06-25 20:05
could you try v 2.1?

**Comment by Tisbox** [comment] 2016-06-25 20:14
The Windows store shows v2.0.1 as the latest version... so I can't yet?

**Comment by matiu** [comment] 2016-06-26 11:41
sorry about thay. So, we know exactly the problem. The key derivation test
will fail if a spending password is set. That was fixed in v2.1.0 but that
version is still under review in the WP store.  Until that is fixed you can
try this workarounds:
- disable spending password, restart copay, check the error is gone, reset
spending password.
- delete and reimport the wallet

thanks for the information understanding this issue

**Comment by RobinTick** [comment] 2016-06-26 16:04
@matiu yes I did have a spending password set before the app update, I can't check the previous versionnumber anymore.

**Comment by RobinTick** [comment] 2016-06-26 16:06
@matiu Windows 10 mobile and I believe Windows Phone 8.1 too auto update apps so we will always be on the latest app version that is released within about a day.

**Comment by matiu** [comment] 2016-06-27 11:19
Closing this since it is fixed in v2.1.0, and there is a workaround for 2.0.x version (https://github.com/bitpay/copay/issues/4444#issuecomment-228597117).

Thanks a lot for your help solving this issue.

**Closed by matiu** 2016-06-27 11:19 UTC
Labels: Support Request
