### ISSUE TITLE
Copay requires a high fees

### ISSUE THREAD

**Issue by kerohero** [bitpay/copay#5164] opened 2016-12-07 20:16 UTC
I'm trying to send a 0.0005 btc to another wallet the super economy fee for sending 0.0005 btc is more than 0.0005. I talked to bitpay support and they said
"In unusual cases like these, this usually means that you have received a large number of transactions/inputs which need to be combined to make one transaction.
Please post your inquiry at https://github.com/bitpay/copay/issues and a member of our Copay team will follow up with you directly.
"

**Comment by gabrielbazan7** [comment] 2016-12-07 20:42
There is not an issue there. Is a bitcoin limitation. The parameter used for the fee calculation is the TX size, not the output amount.

**Comment by JDonadio** [comment] 2016-12-07 20:49
To clarify a little: as BitPay support team mentioned, that's exactly what happen when you have many small inputs in your wallet, so you need to use all (or most) of them to build the transaction and your fee will be increase depends on that.

If you have one transaction with 1 BTC and try to spend 0.5 BTC, the fee rate will not be the same if you have many transactions with small inputs there.

**Comment by dabura667** [comment] 2016-12-07 20:51
Proper fees for bitcoin transactions is based on a bitcoin per bytes rate.

0.00000001 bitcoin is called 1 satoshi.

https://bitcoinfees.21.co/ This site says the current cheapest fee for next block is 80 satoshis per byte... however, super economy would probably be around 20 satoshis per byte.

Now to figure out the size of your transaction in bytes.

If I receive 1 BTC once, and try to send any amount of money. my transaction will be around 259 bytes.

If I receive 0.5 BTC twice (1 BTC total) and try to send anything over 0.5 BTC, I will need to "use" both 0.5 bitcoin pieces I have received, so my transaction will be a little over 400 bytes. If I send less than 0.5 then I only need to use one, so I still am around 259 bytes.

If I receive 0.1 BTC ten times (1 BTC total) and try to send anything over 0.9 BTC, I will need to use all 10 pieces, so my transaction will be over 1500 bytes.

So if we take 0.0005, which is 50000 satoshis, and divide by 20 satoshis/byte, we get 2500 bytes (ish) which is probably around 18-20 bitcoin "pieces" being used.

When you receive a small amount of bitcoin, you will eventually have to pay for that transaction through byte size later on, so "faucet" websites say they are sending you $0.05 at a time, but in actuality, those tiny payments also add on to your future fees... so it is not economically viable to use unless you have them sent to you in larger batches.

**Comment by kerohero** [comment] 2016-12-07 21:13
So there is no way to do anything with the 50,000 Satoshi?! I'm actually collecting them from faucets..

**Comment by kerohero** [comment] 2016-12-07 21:32
While decreasing the fee the transaction takes a longer time to be confirmed some wallets allow you to set the fee even to ZERO, Why something like that isn't included in Copay??!

**Comment by dabura667** [comment] 2016-12-08 02:47
Zero fee transactions will not be confirmed on the network unless you have a friend who runs a large mining pool.

If you do have such a friend, then you can figure out how to make a 0 fee transaction (most wallets do not allow this anymore, because it will make your transaction stuck) by programming your own wallet. Then you can send the 0 fee transaction to your miner friend.

**Closed** 2016-12-13 15:59 UTC

**Comment by miccomservices** [comment] 2017-11-11 13:13
#c

**Comment by rickmts40** [comment] 2020-11-06 05:11
![IMG_20201106_120255_1.jpg](https://user-images.githubusercontent.com/73891504/98328609-b60cb980-2028-11eb-9d4a-16c892152283.jpg)
insane huh?
who in the right mind want to use crypto under insane poorly by design conditions like this. Screw it.
