### ISSUE TITLE
Payment not sent.

### ISSUE THREAD

**Issue by ezepuechi** [bitpay/copay#9191] opened 2018-10-07 18:00 UTC
I used copay to make an online purchase/subscription and it didn't really make the payment for the app and didn't reverse back either. Please I need assistance

**Comment by BGalliotti** [comment] 2018-10-08 13:57
Hello 
Thanks for reaching out to us.

- **Please send us the BitPay/Copay Wallet ID and the transaction hash / ID or the link so we can further investigate and address your inquiry.**

- To get your Wallet ID, open your Copay/BitPay application, then go to `Settings` > [Your wallet] > `More Options` > `Wallet Information`. 
On your phone, if you tap on the wallet ID it will copy it to the clipboard so you can paste it in your e-mail. 
You can do the same on your computer by clicking on the wallet ID.

- The transaction hash / ID is a alphanumeric chain like this: **d0a23876de7cf87574b5cda7557bcc8af5d84f3fd1e6f4c6063fd6b72b0e69ae**

**We look forward to hearing from you.**

**Comment by BGalliotti** [comment] 2018-10-08 19:46
Hello @ezepuechi 
Thanks for reaching out to us.

This is the only transaction you have on the 7th of October:

  [Sun Oct 07 2018 14:41:07 GMT-0300] 3001e963b9b069832e591836a64ee9e017880f41a84a67dbb50fb3d87c3422e0 => sent 0.00137770 btc (fee/kb 0.00020922 btc) (134 confirmations)

If that is the transaction related to the payment, then it is properly confirmed.

If not, you might have done it with a different wallet.

If you have the transaction ID of the payment, you can send it to us so we can further investigate.

Please let us know if you have any additional questions.
Kind regards.

**Comment by ezepuechi** [comment] 2018-10-08 20:41
No thats not the transaction. The transaction was on 4th of October and the
wallet I sent to was 15jtaWzHKWNRZVtVKbJGCdeTdvgYoK5WGR and the transaction
ID is ba4b88375d8d30a5300f252fc1fd850e5cc154ef50855115cb5f15313a0ced72

**Comment by BGalliotti** [comment] 2018-10-09 15:07
Hello @ezepuechi 
Thanks for reaching out to us.

We have researched the transactions and addresses.s
The transaction in question has properly gone through, on our side everything is fine.

There are two possibilities:
- The merchant is taking too much time to provide you with the services/products, in such case you should contact them. Remember you have the proof of the transaction.

- You have sent the funds to an incorrect address. Since Bitcoin transactions are not reversible, there is nothing that can be done to recover the funds.

- Have you paid a BitPay invoice? or you simply made a payment by a regular transaction? (BitPay invoice screenshot attached, just in case you do not know it).
![screen shot 2018-10-09 at 12 06 23](https://user-images.githubusercontent.com/38531900/46678809-d5238d80-cbbb-11e8-839a-6fc242e46679.png)

Please let us know if you have any additional questions.
Kind regards.

**Comment by Amolrada2442** [comment] 2018-10-11 09:19
18fhfWby4dMSrMShbAczumTSwDy6cNzKYZ

**Comment by BGalliotti** [comment] 2018-10-11 14:40
Hello @ezepuechi 
Thanks for reaching out to us.

> 18fhfWby4dMSrMShbAczumTSwDy6cNzKYZ
- What do you mean by this?

There are no wallets related to this address, also there are no transactions involved with it: https://insight.bitpay.com/address/18fhfWby4dMSrMShbAczumTSwDy6cNzKYZ

Please send us clearer answers so we can properly address the issue.

We look forward to hearing from you.

Kind regards.

**Comment by BGalliotti** [comment] 2019-01-11 14:04
Hello @ezepuechi 

**We have not heard from you in while!**

**Are you still experiencing an issue?**

We are going to close this thread, please if you need further help, open a new one explaining the issue in detail, providing all the relevant information possible, we will be happy to help you :)

Kind regards.

**Closed by BGalliotti** 2019-01-11 14:04 UTC
