### ISSUE TITLE
Sent bitcoin with normal fee on January 1, 2018....still stuck sending.

### ISSUE THREAD

**Issue by luckykcc17** [bitpay/copay#7775] opened 2018-01-07 14:59 UTC
![cbe285d5-f32e-4384-a374-d82c3be4ebb4](https://user-images.githubusercontent.com/34752144/34650586-7d1ec4d6-f391-11e7-9eb2-849e4b09c567.png)

**Comment by luckykcc17** [comment] 2018-01-07 15:00
What do I do here to fix this and get back my bitcoin???

**Comment by RaneLiteas** [comment] 2018-01-07 15:23
Having the same issue. They don’t even respond to your problems! A lot of customers are having problems with the wallet and they haven’t received and solutions from Bitpay whatsoever! I am reporting them to the BBB!!

**Comment by luckykcc17** [comment] 2018-01-07 15:37
When I search the address on blockeconmics.com I see one positive and one negative transaction.
![24657c06-4b01-4532-82a3-6c83bcfe88c0](https://user-images.githubusercontent.com/34752144/34650911-b8719a2c-f396-11e7-97e3-bdc9d0759dcf.jpeg)

**Comment by luckykcc17** [comment] 2018-01-07 15:39
I guess I will do the same today and repost to BBB. I habe like 5 smaller transactions as well that I sent with,low fee that are sending.....it is like they are stealing. And customer service does not respond at all.

**Comment by RaneLiteas** [comment] 2018-01-07 15:44
YES THEY ARE DEFINITELY STEALING!! Some transactions they allow to process and others they don’t so that it doesn’t look too suspicious!!! They stole $700 from me!! Everyone with an Issue needs to report them to the BBB cause they a fraudulent!

**Comment by luckykcc17** [comment] 2018-01-07 15:47
Ok....going to report to BBB now....this is I sane. I have never seen anything like this.....

Does support ever respond???

**Comment by RaneLiteas** [comment] 2018-01-07 15:50
I’ve contacted them several days ago concerning my issue and haven’t heard nothing from them! They don’t even respond to these threads either! And I’m sure they see all the complaints that are being made! It’s ridiculous!! Everyone wants to steal from you now, a lot of these types of companies can’t be trusted, they want your coins!

**Comment by Keensyst** [comment] 2018-01-07 18:49
If I receive it I will be very surprised, and thankful.

**Comment by luckykcc17** [comment] 2018-01-07 20:17
@Keensyst what do you mean if you receive it??? Not sure what you wrote makes sense....

**Comment by Keensyst** [comment] 2018-01-07 21:05
I can't receive any money either,

**Comment by yasminsalim** [comment] 2018-01-07 22:05
my transaction is still unconfirmed from last 5 days.

my unconfirmed transaction is not showing on my wallet. its available on blockchain.

In bitpay android app, BTC balance change on every refresh.

i am not getting any response from bitpay support.

**Comment by RaneLiteas** [comment] 2018-01-08 06:14
HEY GOOD NEWS I FINALLY RECEIVED MY BYC DEPOSITS AFTER ALMOST A WEEK!!! Just transferred it out..let’s see how that goes!!!

**Comment by malekcsgo** [comment] 2018-01-08 13:19
here is my thrread (https://github.com/bitpay/copay/issues/7734) can someone help me i have the same issue what is BBB ? how can i report too ?

**Comment by luckykcc17** [comment] 2018-01-08 17:07
@RaneLiteas That is great news for you....I hope that happens with me too. I have about $100 in outstanding transactions that are still just "sending." I reported to BBB because BitPay's customer service doesn't seem to exist and that is unacceptable.

**Comment by Keensyst** [comment] 2018-01-09 01:40
,
On Jan 8, 2018 11:07 AM, "luckykcc17" <notifications@github.com> wrote:
>
> @RaneLiteas That is great news for you....I hope that happens with me
too. I have about $100 in outstanding transactions that are still just
"sending." I reported to BBB because Bitpay' See​ customer service doesn't
seem to exist and that is unacceptable.

**Comment by carlosgfranco** [comment] 2018-01-14 21:07
Similar to https://github.com/bitpay/copay/issues/7807

**Closed** 2018-02-07 01:55 UTC
