### ISSUE TITLE
PAPER WALLET SWEEP

### ISSUE THREAD

**Issue by BLAGZ84** [bitpay/copay#7605] opened 2017-12-22 02:38 UTC
I swept my bitcoin paper wallet into my Copay walet on the 21/12/17 at about 11pm AWST. It has now been about 12hrs and my funds have still not been confirmed.
It still says RECEIVING.
It also says that due to the low fees set by the sender, the transaction might take a long time or be dropped altogether..

How long will it take??

Insight now says transaction not found

My Copay wallet ID is;
7afafe00-bf39-4f6d-a434-2a5ff21945b5

The wallet address with a balance showing is;
1MQTi4VyWoSdnKFU4Ch5ptnH4BGEPfVKJ3

but it is not confirmed and therefore available.

Please advise asap.

I need help.

**Comment by cleto123** [comment] 2017-12-22 17:21
Sorry I don't have an answer. I just wanted to say that I've experienced the same thing and am on your side of this. What to do?

**Comment by BLAGZ84** [comment] 2017-12-22 17:23
What happened with you?

**Comment by cleto123** [comment] 2017-12-22 17:28
I wanted to try a new bitcoin atm in our town for the first time, so I put in $20. It charged me $3.98 in fees and I sent $16.02 in bitcoin to my Bitpay wallet address. It confirmed it had been sent via email, and when I checked my wallet it said that it was being confirmed. That was 2 days ago. I just checked my wallet and it is gone! It was never on the blockchain and I even looked it up via the transaction id#. nothing!

**Comment by BGalliotti** [comment] 2018-04-20 16:15
Hello,
sorry for the delay, we are re-arranging our support tickets to improve our service. 
Since this thread did not have any responses in a while we will be closing it.
Please if you still need support, open a new one, we will be happy to help you.

Thanks.

**Closed by BGalliotti** 2018-04-20 16:15 UTC
