### ISSUE TITLE
Feedback and concerns about the new v3 UI

### ISSUE THREAD

**Issue by Willstar44** [bitpay/copay#5808] opened 2017-03-23 06:43 UTC
why did you change a good thing with the old UI , it was so much better seeing the balance on the main page , a simple click or send and receive , 

All you have done is clutter up the screen with more junk we don't need

**Comment by astupidmoose** [comment] 2017-03-23 08:27
The new chrome UI is horrible and makes me not want to use it at all. Copay has always been a very user friendly UI and I feel like the updates in this newest version go against that. It honestly has made me ditch the chrome update and go to my phone exclusively. If this is the future of the copay wallet, i'd be very upset. 

Couple issues right out the gate: 

1. Why has the amounts/address been split into 2? This was fine as one screen. 
2. Amounts are rounded to 6 digits, this is an accounting nightmare. I use bits in my day-to-day transaction logs for accounting and now I cannot see the full value of a transaction because its rounded. It used to be you would go into the transaction to see the full value but thats gone now. 
3. Regenerating new addresses when receiving funds seems to be hidden, so well that I cannot find it.

**Comment by bitjson** [comment] 2017-03-24 00:34
Thanks for taking the time to send us feedback @Willstar44 and @astupidmoose! 

Very sorry you've not been happy with parts of the new design – we'll definitely be reviewing this feedback, and I hope we can break this issue into some actionable improvements.

**Comment by astupidmoose** [comment] 2017-03-24 04:20
I hope its OK if I continue to add see things I see as issues. 

the "Send Max" button is now hidden. This was easily selectable from the transaction in the past, however now needs to dig into a new menu to do this.

**Comment by rileyjalexander** [comment] 2017-03-24 16:34
I have a SUBSTANTIAL issue with new UI. 

I have an incoming wallet that utilizes XPUB to create new payment aliases on a website that I sell items on. I used to always have to go to the wallets ADVANCED screen, then "Wallet Information", and then "Scan Addresses for Funds" 

This feature is GONE as far as I can tell. Please help, I have no way to check for my funds that come in now.

**Comment by astupidmoose** [comment] 2017-03-24 16:39
@rileyjalexander Heres how you find it:

Click the "Receive" button, Scroll through your wallets to find the wallet you need. *Clicking Receive automatically selects your first wallet and not necessarily the wallet you were just in or the wallet you want to use*. Once you have the right wallet, Click the address which brings you to the wallet addresses screen. From here you can now scan for funds. 

I struggled finding this as well this morning, its super hidden.

**Comment by rileyjalexander** [comment] 2017-03-24 16:44
@astupidmoose Thank you so much. I NEVER would have found that. lol

**Comment by paintballpanda** [comment] 2017-03-28 21:37
@astupidmoose Thank you for the information on how to find the "Scan Addresses for Funds" section. Was just about to switch to a different app but figured I'd check here first. Thank you!

**Comment by toomim** [comment] 2017-03-31 22:27
Wow, the new UI has big problems, I'm about to switch away from copay! It just led me to send a huge amount of money to the WRONG ADDRESS. I might have lost this money!

Task: I wanted to get a receive address for one of my wallets to send money to.
  1. So I click on the wallet in the home screen
  2. Then I click on "Receive" at the bottom
  3. It shows me an address. But this is the address for a TOTALLY DIFFERENT WALLET.

Jesus this is such an obvious bug! Wallets need to support sending and receiving money!

**Comment by toomim** [comment] 2017-03-31 22:31
Here's another bug:

Task part 2: Copy the address to clipboard so you can paste it somewhere
  1. On the receive screen, it only shows me PART of the address. So I can't even read it. Or select it.
  2. There's no way to copy the address from here
  3. If you click on the address, it takes you to a new screen. Nothing at the top of the screen shows you the address. You actually have to SCROLL down into a list of addresses, and try to identify which one in the list you want to use, and then click on it, and cross your fingers and hope that you chose the right one.

What the heck guys? The primary feature of a wallet is being able to PUT MONEY into it!

And here's another bug: once I reached that "advanced wallet addresses" screen, the back button disappeared! I had no way to return to the home screen. I had to force quit the app. Just because I wanted to get a receive-money address!

**Comment by toomim** [comment] 2017-03-31 22:32
Here's another problem:

On that advanced "wallet addresses" screen, it doesn't tell you which wallet you're looking at the addresses for! If I'm about to send a bunch of money, I want to be sure that I'm using the right address! How can I be sure that these are the right addresses? I have to click back (if the back button is there) and read the wallet, and then go back and read the address on a different page?

**Comment by toomim** [comment] 2017-03-31 22:40
Here's another bug: the confirm page UI is flat out failing to show the amount I'm sending!

![image](https://cloud.githubusercontent.com/assets/101208/24571764/3b421e60-1628-11e7-85b2-9b9b3041091e.png)

What's happened? Is the company alright? Are you still supporting this software? Should I switch to something else?

**Comment by gabrielbazan7** [comment] 2017-03-31 22:57
First issue: If you want to copy an address you must go to the "receive" tab, choose the wallet and there it is. Tabs must be independent. Nothing you do on one tab should effect the current navigational state of other tabs, thats the "tab" principle... all apps works like that. So if you look at the history of a wallet in the home tab, it doesn't mean you will get the address of that wallet in the receive tab.

**Comment by gabrielbazan7** [comment] 2017-03-31 22:58
Second issue: click on the QR to copy to clipboard.

**Comment by gabrielbazan7** [comment] 2017-03-31 23:02
Third issue: That's an ionic bug. It was fixed, but not yet tagged. https://github.com/driftyco/ionic-v1/pull/210 . Sorry about that, should be fixed in Copay soon.

**Comment by astupidmoose** [comment] 2017-03-31 23:03
@gabrielbazan7 In Regards to the First Issue @toomim had, This is horrible UX. If you are in a wallet, you should be able to hit "receive" while in that wallet and automatically have the receiving address for the wallet you were just in, not an entirely different and random wallet. This is how the majority of bitcoin wallets I have ever worked with react. That's also how copay worked before the update and it made sense. The redesign adds unnecessary steps and over complicates what used to be one of the greatest wallet, especially for beginners.

**Comment by gabrielbazan7** [comment] 2017-03-31 23:07
Fourth issue: The "Wallet Addresses" view, gives you information about the wallet you choose in the last view. If you click in the address "xxxx" of the wallet "X" that means that is the information of the wallet "X".

**Comment by bitjson** [comment] 2017-03-31 23:08
> 1. So I click on the wallet in the home screen
> 2. Then I click on "Receive" at the bottom
> 3. It shows me an address. But this is the address for a TOTALLY DIFFERENT WALLET.

That seems to be a common expectation from previous Copay users – we probably need to revisit the Receive tab to make that clearer. In user testing with new users, most users noticed the cards at the bottom of the receive tab, and didn't expect the tab system to be "stateful" (e.g. Facebook, Twitter, etc. mobile apps). Since Copay has done that for a while, it's definitely throwing off Copay users. 

Thank you all for the excellent feedback. We definitely see multi-wallet as the future direction for the app (lowering the barrier to using many wallets fluidly), so we'd like to avoid re-introducing the concept of a "current" wallet. But we will definitely look into how we can make the Receive view more intuitive. (Would love to hear ideas from anyone interested!)

**Comment by toomim** [comment] 2017-03-31 23:08
That design just caused me to send $10,000 to a wallet that isn't even in use anymore, and almost lost $10,000. Two of the copayers has since deleted the app, because we weren't using the wallet. I barely got 3 other copayers to find their private keys and recover the money.

If Computer Science PhDs are losing $10,000 due to the confusing UI in your app, then there's a problem in the UI.

I've been promoting Copay for the last year. But now I am telling everyone I know to transfer money out of it. I have been raging mad for the last 60 minutes trying to correct the loss of this money.

**Comment by bitjson** [comment] 2017-03-31 23:12
@toomim would you be interested in seeing the mocks/beta for improvements to the Receive tab? It sounds like you'd be able to give us some really valuable feedback.

**Comment by gabrielbazan7** [comment] 2017-03-31 23:12
About the fifth issue maybe you could give us more information so we could fixed, maybe the log or the steps to get to that empty view.

**Comment by toomim** [comment] 2017-03-31 23:13
@bitjson This is not just because the old Copay behaved like that. It's because it's the only sane way for any bitcoin wallet to work.

If I click on a wallet, and then click on receive, it is insane for it to give me the receive address for a different wallet. Why would I want a RANDOM wallet's receive address? Is this a casino?

There's no use case for choosing a random wallet. That's just wrong.

**Comment by toomim** [comment] 2017-03-31 23:13
@bitjson Feel free to facetime me: toomim@gmail.com

**Comment by toomim** [comment] 2017-03-31 23:18
You can also imessage or sms me at 510-282-4312. I am happy to give design feedback.

**Comment by astupidmoose** [comment] 2017-03-31 23:20
I have no issue with Multiple wallets being listed on the bottom of the receive screen, however it should I feel default to the wallet which you were last in. This would improve the workflow of the user. 

Right now I have 5 Wallets, call them A, B, C, D, E

If I click the home and Navigate to A, then click "receive" Wallet A should be selected on the bottom tabs. Leave the ability to change it as well, however just default to the last worked with wallet. I don't think anyone would argue that if your viewing Wallet A and hit receive, you want Wallet C to be the default.

**Comment by bitjson** [comment] 2017-03-31 23:23
If anyone else reading this issue would be interested in providing feedback on future designs for the Receive tab, please shoot us an email at feedback@bitpay.com, we'd love to work with you.

**Comment by toomim** [comment] 2017-03-31 23:32
The "cards" at the bottom do not look like cards. You can only see one at a time. That means that it's not clear that you can select a different one.

This icon:

![image](https://cloud.githubusercontent.com/assets/101208/24572635/33ced270-162f-11e7-88bb-934046f958be.png)

...is vague. I could not tell what it meant. I could not tell that I could choose a different wallet by clicking on it.

It is not clear that the address shown above is coming from the wallet shown below. There is a very subtle grey triangle inlay that might suggest that, but that's not clear.

The wallet is shown AFTER the address, but it comes BEFORE for the user's task. The user's task in receiving money is (1) specify which wallet they want money from, and then (2) copy the QR code or bitcoin address. But with this design, the user has to go from bottom to top. That's bad. Humans process screens from top to bottom, left to right.

I could list more problems.

**Comment by toomim** [comment] 2017-04-15 02:01
Hey guys, do you do any user testing on desktop?

The "swiping a card" at the bottom for accounts is not intuitive on desktop, and displays the wrong cursor.

In order to change accounts, you have to drag and drop a card with the mouse. But drag and drop is not an easy operation with a mouse. And if you DO need drag and drop, you should use a "grab" cursor ![image](https://cloud.githubusercontent.com/assets/101208/25059890/76b543d8-2144-11e7-862b-c3d118218012.png) or a "pointer" ![image](https://cloud.githubusercontent.com/assets/101208/25059892/808c870e-2144-11e7-8151-c0bd5e41d61a.png) but right now it's using a default arrow cursor: ![image](https://cloud.githubusercontent.com/assets/101208/25059893/89e5856c-2144-11e7-8521-00fd3dda08b5.png).

If you didn't run into the problem selecting a wallet in your user testing, it sounds a lot like you didn't test with any desktop users. I recommend you give it a shot.

Also, ask them to try copying the bitcoin receive address to the clipboard. I bet they will find it confusing. You are making them click on the QR code right now! That doesn't make sense when you have a mouse cursor.

**Comment by toomim** [comment] 2017-04-15 02:12
Also, when something is *clickable* you should use the pointer icon: ![image](https://cloud.githubusercontent.com/assets/101208/25059892/808c870e-2144-11e7-8151-c0bd5e41d61a.png)

But none of the cards are showing up as clickable. It displays no pointer icon. So changing accounts is not discoverable on desktop. 

Finally, it would be way better if you reversed the order and put the account selection on TOP. Users need to select their account *before* they grab its bitcoin address, and actions in a user-interface should proceed top-to-bottom, left-to-right, in the same order that western people read.

Thanks for reading! I hope the UI gets better.

**Comment by toomim** [comment] 2017-04-15 02:39
Also, consider that there are *two* different UIs for selecting wallets in the new version of copay:

1. On the home screen, there's a vertical menu of wallets, with left-set typography, non-bold, displaying the k-of-n multisig type, and a ">" arrow at the right, that you select by tapping on to scroll the menu to the right.
2. On the receive screen, there's a horizontal list of "cards", each of which have a **bold name** and do not list their multisig type, and you move amongst with drag and drop from left to right.

This breaks the principle of [consistency](https://www.interaction-design.org/literature/article/principle-of-consistency-and-standards-in-user-interface-design) in UI design. The user interface should use a consistent UI mechanism for selecting wallets in all parts of the UI.

Furthermore, this is a strong indicator that there should not be two separate places to select your wallet in the first place. It's likely that the tab bar at the bottom was a mistake. If you just have people choose a wallet first, and THEN show them all the things they can do with the wallet, you don't need two different UIs — you don't even need two different places to choose a wallet! You just choose the wallet once, in one place, and then work with it. This fundamental change simplifies the entire UI design and eliminates these inconsistencies.

If you didn't choose to design two different UIs for selecting a wallet, you would also save design time. You wouldn't have to polish and perfect the UI in both places. You wouldn't have introduced the UI bug with the cursor pointer type. I recommend simplifying the app. It'll save you development time, give you more time to polish the elements you have left, result in fewer UI bugs and less user confusion, and also save users time because there will be fewer screens to click through to accomplish their tasks.

**Comment by dabura667** [comment] 2017-04-16 03:01
ACK the new UI is confusing to existing users and small UI changes (like going from a wallet home screen to receive tab defaulting to the first wallet rather than defaulting to the wallet that was just shown etc.) can cause users to be mistaken.

I highly agree with every point @toomim made thus far and look forward to a UI update.

That being said. When sending $10,000 by ANY method. I personally quadruple check every aspect of any screen and text being displayed to me... so unless your old unused multisig and your everyday used multisig wallet had the exact same wallet name, (which I would never recommend using the same name for two wallets) I highly doubt I would make the same mistake in your position. I am very relieved that you were able to recover your money, though. :-)

**Comment by dskloet** [comment] 2017-05-07 10:35
I also sent money to a wrong address, for a wallet that I didn't even create and never used and that was not backed up. This is ridiculous. Choosing a wallet should be the top-level choice. And that's what it looks like on the home screen. But when I switch to the receiving tab you silently switch me to a wallet that I have never used.

This is not about being used to something. This is a fundamental design flaw. But if you want people to choose a wallet on each tab, you better *force them to choose* rather than showing a random different wallet.

**Comment by rodbishop** [comment] 2017-07-22 09:38
CoPay used to be a master work of great design. Very disappointed by the new release. Have been battling it for months now. Each failure is minor but they add up together. Some issues in no particular order: 

a) Wallet-settings used to be clearly differentiated from app-settings, but now I can't easily find Wallet-settings; 

b) Send and Receive used to begin from a wallet, so intent was clear, now send and receive are global it's harder for me to specify my intent 

c) Send Screen used to show available balance in the wallet, now you must write it down, remember or guess 

d) Send Max feature was useful and obvious, now is hidden; 

e) If a transfer leaves insufficient funds to pay fees, then the fees amount are not shown, so it's impossible to know what a correct amount would be; 

f) fees are denominated in Satoshi, even if the rest of the app is in BTC or Bits. How many Satoshi in a Bit again? Don't recall, have to check.

f) In general styling, fonts and layout were newbie friendly, now in general more technical, more power-user. Newbie-friendly was better.

g) Last issue is probably a bug, iPhone 6 and 6S, when I visit a wallet there are often no menu items on the bottom of the screen. Sometimes there, sometimes not. I find that I can force them to appear if I do a half-swipe left.

Thanks for reading, and sorry for being critical. But I was in love with my old app. This is a solid step backwards. Happy to provide testing and advice if that is useful.

**Comment by BitMari** [comment] 2017-09-10 20:14
how can I get the old interface back on the new code , it this possible?

**Comment by JDonadio** [comment] 2017-09-11 20:58
> how can I get the old interface back on the new code , it this possible?

I'm afraid not. You can check the [releases section](https://github.com/bitpay/copay/releases) and download an old version instead.

**Comment by jooize** [comment] 2017-09-18 00:40
> g) Last issue is probably a bug, iPhone 6 and 6S, when I visit a wallet there are often no menu items on the bottom of the screen. Sometimes there, sometimes not. I find that I can force them to appear if I do a half-swipe left.

Happened for me on iPad 12.9″ with iOS 11. Haven't been able to reproduce.

**Comment by BitMari** [comment] 2017-12-05 00:35
hi guys is there anyway at all I can get to develop in some way and use the old interface on the new or latest Copay?

**Closed** 2019-01-11 19:33 UTC
Labels: Design Needed
