### ISSUE TITLE
incorrect fees

### ISSUE THREAD

**Issue by maxguzenski** [bitpay/copay#3941] opened 2016-03-01 14:09 UTC
I setted copay to use a priority tax fee (0.000489) and did a transfer, it is 15h waiting to confirm because the real fee paid was 0.0000418

https://blockchain.info/tx/825f887bcabeb48a0411031df926327bd999829d52c692c0d3619f283c8d1fdf

(right now it yet not be confirmed!)

**Comment by matiu** [comment] 2016-03-01 15:27
We checked the TX in the database and it was sent with `economy fee`. Would it be possible that you have not set `priority` before sending the transaction? What version/platform of Copay are you using?

**Comment by maxguzenski** [comment] 2016-03-01 21:46
It is setted to priority for sure, I was with 1.6.3 ... now I have the latest (1.8.3) but I yet not move any bitcoin with this version. 

I user it on Macbook, OSX el Captain

**Comment by isocolsky** [comment] 2016-03-02 12:56
Looks confirmed now. FYI in the upcoming version of Copay there will be a way to check the final fee of a transaction before sending. Hopefully this will help detect any potential problems. I'm closing this one for now. Please reopen if you keep having issues. Thanks.

**Closed by isocolsky** 2016-03-02 12:56 UTC

**Comment by isocolsky** [comment] 2016-03-05 22:08
Just for the record, we found an issue that could have been the culprit in this case. If Copay was unable to get fee values from the server (in most cases due to poor connectivity or network issues), a hardcoded value of 100bits/kB was being used. This worked well in the past but recent surge in transactions has made this value too low. This PR https://github.com/bitpay/copay/pull/3950 removes this default preventing any txs to be created with low fees. The change will be available in the upcoming version of Copay.
Thank you for your report!
