### ISSUE TITLE
Bug: UI glitch and Wallet_Busy

### ISSUE THREAD

**Issue by caveman1973** [bitpay/copay#8420] opened 2018-04-12 14:35 UTC
App doesn't work properly in my iPhone SE. 

Home screen doesn't render properly (pic: https://s18.postimg.cc/nao9r9zx5/75184741-0_CC7-4_B3_C-_B6_ED-28341_BB3171_C.jpg)

Two days since I cannot use the app:
Pic: https://s18.postimg.cc/ocyga0t2x/FC91_E3_FA-_C5_FD-4_BB3-_B328-1_D7232_C1_C444.jpg

**Comment by shaun-ba** [comment] 2018-04-12 14:56
Take screenshots of your balance, ours has just decreased by 40% with no record of why.

**Comment by Gamboster** [comment] 2018-04-12 15:33
Hello @caveman1973 
Regarding the first image: Thanks for report it, I could reproduce it. We will send a fox for that, soon.

Regarding the second image: Our wallet team is currently working to resolve a backend service issue affecting BitPay and Copay users. We appreciate your patience!

**Comment by Gamboster** [comment] 2018-04-17 18:33
The error mentioned in the first image was solved in this Pull request (https://github.com/bitpay/copay/pull/8453) 
You can see it working normally in the next release.

Regarding the second image, it was solved days ago. I'm going to close this ticket.

Regards.

**Closed by Gamboster** 2018-04-17 18:33 UTC
Labels: Minor Bug

**Comment by gboelter** [comment] 2018-05-03 10:54
Looks like the issue from second screenshot Is back ...
