### ISSUE TITLE
Missing two-digits in BTC unit

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/copay#2676] opened 2015-05-03 19:19 UTC
![copay_-_multisignature_wallet](https://cloud.githubusercontent.com/assets/237435/7446475/244394d0-f1b0-11e4-998b-515eaee99e07.png)

**Comment by rustyn** [comment] 2015-05-04 20:08
I'm pretty sure that is by design and not an actual issue

**Comment by Giszmo** [comment] 2015-10-27 02:44
Duplicate of issue #3125.

**Closed** 2015-11-28 14:46 UTC
Labels: lowprio
