### ISSUE TITLE
Broadcasted TX (BCH) not found. Funds locked. Want to rebroadcast.

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#8322] opened 2018-03-27 15:49 UTC
I have created a transaction and it is not confirming. Funds are locked. If I try to "see it on the blockchain", the insight servers do not see it at all - not unconfirmed, or anything. I get "Transaction not found".

I have tried clearing the cache for the accounts and also scanning address for funds, in that order.

There must be a way to rebroadcast this transaction, or remove it from the client. Any guidance?

**Comment by bigboybiggs** [comment] 2018-03-27 16:38
I have same issue and have been waiting for copay to respond for almost a week with no success. There is a number of people with same scenario

**Comment by webbasedmoney** [comment] 2018-03-27 17:43
^^ have the same problem here. Sent from copay 3.14.1 to the Current CashAddr translated receive address.
Still pending unconfirmed in copay, not found in insight. Nothing showing at Receive address. 

Help us out guys, please.

**Comment by CodersBrothers** [comment] 2018-03-27 17:52
The same here. My Copay Wallet not confirm. And the wallet seed not shows the balance in other wallets like electron cash. Some clue what is happening? Maybe a hack?

**Comment by bigboybiggs** [comment] 2018-03-27 22:57
I also have same issue. I'm beyond pissed that COPAy is taking so long to even acknowledge the issue  I do not believe it is a hack. Previously it said it was a network error which would make sense why it's not
Showing on blockchain. In re to resolving and getting us access to our $$$, this will need to be done with COPAy unless we can somehow sync our accounts once network issue is resolved

**Comment by imaginaryusername** [comment] 2018-03-27 23:37
The issue is probably with the Copay backend, since these transactions aren't broadcast and not even seen on Insight. While Bitpay drags their feet and refuse to respond, you can unlock your wallet in Electron Cash (desktop). 

1.  Download from [electroncash.org](electroncash.org), install per your platform. I do not recommend the Android version, just use the Windows/Mac/Linux flavors.
2. Pick name->Standard wallet -> choose "I already have a seed". If you already have your own Electron Cash wallet, click File -> New/Restore to get here.
3. Type in your Copay backup seed. Click Options, check "Bip39". You should now be able to click Next.
4. On the next screen, change from 44'/145'/0' (Electron Cash's preferred seed path) to 44'/0'/0' (Copay's preferred seed path). Click Next. 
5. The wallet is created, wait a few moments for it to scan, you should see your history minus your stuck transactions. Spend the wallet to somewhere you like. 

Hope this helps.

**Comment by CodersBrothers** [comment] 2018-03-28 17:54
Not valid for me. The seed dosnt have as own address the return address that copay wallet set in the first transaction. So with this, my wallet have 0 BCH

**Comment by imaginaryusername** [comment] 2018-03-28 17:57
@CodersBrothers did you change the derivation path? Don't skip that part, else Electron Cash will be monitoring the wrong addresses.

**Comment by CodersBrothers** [comment] 2018-03-28 19:02
I'm using the standard: m/44'/0'/0'

Let me explain:

Copay is showing this in my wallet

![captura de pantalla de 2018-03-28 20-50-45](https://user-images.githubusercontent.com/2166523/38049909-b73ac436-32c9-11e8-9b4e-f51cb816e371.png)

The balance, and the sending payments, not are real due to the Bitpay servers, ok perfect. This not is my problem. I can use other wallets. My real problem is this: when I create a new wallet with the Copay Seed in Electron Cash, for example, its shows this:

![captura de pantalla de 2018-03-28 20-49-16](https://user-images.githubusercontent.com/2166523/38049847-8e17b5e6-32c9-11e8-96ca-fe9fa6140ee5.png)

Only 2 transactions!! the initial deposit and one payment. And the two outputs are not mine, one is normal (not is mine), but the other is the traditional refund address... but not, the refund address not is part of the HD wallet, the address is 1CK5bd4vdjUaZLAH15c1B9RNnY8VDyC4gn (or this qp7pfd2sf0dpr9aj54hgqcvwp7fyq4xzq5dcl7fgjx)

![captura de pantalla de 2018-03-28 20-57-04](https://user-images.githubusercontent.com/2166523/38050229-983bd70e-32ca-11e8-8c05-34506aac0c39.png)


![captura de pantalla de 2018-03-28 21-00-06](https://user-images.githubusercontent.com/2166523/38050371-08e5a08e-32cb-11e8-8bd5-715ddea6fbe9.png)


Is incredible because after the first trandaction, in Copay wallet I done other transacction with no problems, so Copay wallet have the private key, but this address neither is mine. You can follow here the spents https://bch-insight.bitpay.com/address/qp7pfd2sf0dpr9aj54hgqcvwp7fyq4xzq5dcl7fgjx

CONCLUSION: BitPay with Copay sent the refund amount to other address that I don't have the seed.

**Comment by imaginaryusername** [comment] 2018-03-28 19:08
@CodersBrothers If you recover in Electron Cash using the 44'/145'/0' path by default for BIP39, it might do that. Copay uses 44'/0'/0'. Let me repeat: When recovering, did you change the derivation path to 44'/0'/0' ?

**Comment by CodersBrothers** [comment] 2018-03-28 19:53
@imaginaryusername yes, I use m/44'/0'/0'

![captura de pantalla de 2018-03-28 21-51-49](https://user-images.githubusercontent.com/2166523/38052691-642955ec-32d2-11e8-96f7-ff5aacbf5e6d.png)

**Comment by imaginaryusername** [comment] 2018-03-28 19:58
That is extremely odd. Does it do the same thing if you recover in Bitcoin.com wallet? I wrote a guide with two ways to do it: https://www.yours.org/content/howto--recover-stuck-copay-funds-679e94768817

**Comment by CodersBrothers** [comment] 2018-03-28 22:14
Amazing @imaginaryusername . Solved! Bitcoin.com wallet solved the problem. He detected the amount and was possible move the funds. For any reason only with the backup was possible, not with the seed. Seems that the backup describe the perfect derivate path. Thanks.

**Comment by JulianTosh** [comment] 2018-04-09 01:31
Still not solved for me. There has to be a way to rebroadcast a TX or at least clear the TX out of my cache. This sucks.

**Comment by bigboybiggs** [comment] 2018-04-11 05:54
I have yet to even be contacted by support. I had create wallet on a separate phone just to be able to use Btc again

**Comment by imaginaryusername** [comment] 2018-04-12 14:24
At this point it's probably better to recover the wallet elsewhere (see above), ditch Copay and move on. They updated their client side wallet _twice_, but clearly has no intention of fixing their backend.

**Comment by JulianTosh** [comment] 2018-05-02 03:45
It's been over a month now since I created this ticket. I've re-imported the wallet to the latest version and I still get the same error: 1) The wallet immediately shows locked funds, and 2) Insight has no knowledge of the transaction when I try to "view it on the blockchain".

This is currently locking up a non-insignificant amount of BCH for me and I'd really like to get this resolved.

**Comment by BGalliotti** [comment] 2018-05-02 15:18
Hello @JulianTosh 

Thank you for reaching out to us.

So we can further help, please provide as many of the following details as you can:

- Current device used
- Current operating system for the device
- Current version of the wallet used
- Any log files containing error details
- Error screenshot
- Steps to replicate
- **BitPay Wallet ID - To get your Wallet ID, open your BitPay application, then go to Settings > Wallets & Integrations > More Options > Wallet Information.**

Regards

**Comment by imaginaryusername** [comment] 2018-05-02 16:20
Can confirm the problem still persists on a single user wallet on Android as well. I moved the funds out using Electron-Cash desktop by restoring the seed there, but the phantom tx persists even after it has been double-spent. 

Copay backend really needs to get rid of stale transactions by attempting to broadcast them, and if they don't broadcast, remove them. Log them if there's a need to document a doublespend.

**Comment by matiu** [comment] 2018-05-02 17:29
Hi, thanks for your patience @JulianTosh and others.  This was a temporary backend related problem, and I will need the wallet details in order to review it and solved. Could you please send me the txid or wallet-id affected to matias@bitpay.com so I can check it further?  Same goes to anyone else having this issue.

thanks
matías

Ill close this issue now, please contact me in private to more forward.

**Closed by matiu** 2018-05-02 17:29 UTC
Labels: Support Request

**Comment by JulianTosh** [comment] 2018-05-09 14:00
@matiu 
I send my wallet details to you via email. Never got a response. Funds still stuck.

> On 2018-05-02 10:58, Julian Tosh wrote:
> -----BEGIN PGP MESSAGE-----
> 
> hQIMA8Bnn1xqoy3cAQ/+Jlb8XrjCqr7T4AIQlLOHL/IvKfXKN/yXSKpd8awShzAu
> Q6KUL7sDMyeuhD70brQA+TLkcP2PbfZm8IQFTATa0svgOCVtgEU2lNzNYtzkHlt4
> Xwjmj+HUcB5m+BEkbb9tLN00GaC1hPR3ktIiqCXqtcETjT61vCxikoevm72k1dNw
> nwHViS0LWuGlh8og26PUhVdjYxC4I+RFgUZSh+GlC5gwZDfenoo791rop7bnbiSL
> aSRpOdg1z1uzT2jfeiIkJVkCribSB4l/+rTbxAHnsXM3lOKDUTzbiuUIAMklN2a3
> bnkDjbETn9B+E0ENrOG/C9R0gI16aSAeOG1J2QIChYEgwwTla0LeJRKL2kW4NNDD
> 5bnSziibUDD5nEjlzg+AVr8rystlwdYdCaoClEgVOq56i9uKgg7uBj8MWqfzBvbM
> I+2QdUL1P+gpucespktwifJjKP/oNKXRMQ1EBsgvUhaCCeGUHVziBEtSF0j1eWac
> v43I2OF//+nVibbsZ83b6MNrpex3Ld3uFwY1wnLdp2zojmcKTDNRVCBMZ0jkL7GG
> A/DbLbLCU5dQrDeN91D0c8ep0jNA3UaR6pzgx3JEPq6dy/ZgOc0bdZdprt77D1p2
> Pk1HXv+TnIL3aEgDVetQ67rTaoz2enACnwOafcq9QcSjaIj+VTQfRzt51SDU8hLS
> ewEHVdUYapDpNd0SbTq+Gsauw65YlxH7oibklQu557KO8b3N8B7sSSs7TVZlQi7R
> pTQAP4Bmk6VC3gfmveROcwa+6m+jOfVU+HVqqHctj1EVFSawaNOpDbobSj7GP6GP
> eGWWikJorVeAegnlubALJWphyc9kFHp4QqOBkQ==
> =575U
> -----END PGP MESSAGE-----

**Comment by matiu** [comment] 2018-05-09 14:11
Hi Julian, just saw that, checking now.

**Comment by JulianTosh** [comment] 2018-05-10 13:05
@matiu 

I can now see the transaction details in Insight, but it is not visible on other BCH blockchain explorers. Transaction has been unconfirmed for 24 hours. Funds are still locked in Copay. Please advise.

**Comment by matiu** [comment] 2018-05-10 14:07
Hi. I am sorry for this problem, we will check it during the day amd get
back to you.
