### ISSUE TITLE
Clicking on "Duplicate for BCH" button does nothing, without error message

### ISSUE THREAD

**Issue by chriswilmer** [bitpay/copay#7556] opened 2017-12-20 00:14 UTC
I am trying to recover BCH from a 2-of-2 Copay wallet. Both cosigner A and cosigner B used a Trezor, each using the same 24 word recovery seed but with a different passphrase.

Cosigner A successfully entered the recovery seed to create a software BTC wallet, and then duplicated a BCH wallet, and the successfuly signed an outgoing txn.

Cosigner B followed the same procedure, but at the point of being able to click "Duplicate for BCH" nothing happens. A little loading animation plays for a second but then disappears. No error message or warning is given, and no Bitcoin Cash wallet is created. Hence, cosigner B is unable so sign the txn created by cosigner A. 

Please help!

**Comment by rileyjalexander** [comment] 2017-12-20 23:16
I am basically having this exact issue. I have a 2 of 4 wallet. Cosigner A imported no problem, as you said. 

Cosigner B tried to import, was greeted with all sorts of errors, it showed as if he was setting up a new wallet and it acted like creating a wallet invitation and had red "incomplete" letters. 

Please help. I have a very large amount of BCH that is essentially stuck due to multisig. It appears all the coins in STANDARD 1 of 1 wallets is un-affected.

**Comment by pietjebelkees** [comment] 2018-02-24 23:33
I've sent bch to my btc copay wallet, when I tap settings > bitcoin cash it says that my bch are there, the exact amount. When I tab on duplicate a bch wallet is created but no sign of the bch, I already tried the recovery tool. It says 0 bch. I already checked the transaction, it has been confirmed 2 days ago.

I scanned my wallet, says 0.0 bch

Copay isn't doing anything to fix this? Many people are facing this problem

**Comment by pietjebelkees** [comment] 2018-02-26 08:59
And again the shitty Copay support isn't doing anything about this, well done guys, you've made the worst wallet ever. I hope you're happy

**Comment by rileyjalexander** [comment] 2018-02-26 15:41
pietjebelkees,
I am not copay support, HOWEVER, I will attempt to help you, as I was able to resolve the issue I had. It had to do with needing to make sure I have the LATEST version of copay installed, and then re-importing the 12 phrase backup seeds. Once re-imported, the multisig bch opened up with no problems at all. 

It sounds to me like you might be having another issue/bug. Are you positive that you had that BTC balance in the wallet during the July fork? Or did you recently put the funds into that wallet? It could be a bug simply where it is saying you have BCH by mistake when you really dont. 

And for the record, I would not be bashing copay. Copay is actually one of the most secure mobile wallets that I have ever used, and I have been in the bitcoin space over 5 years.  It is the only multisig wallet that I trust with funds. 

Also, for the record: Copay Wallet = Bitpay Wallet = Bitcoin.com Wallet. They all use more or less the exact same source code with just minor modifications, but it all was written by Copay Dev's (funded by Bitpay)

**Comment by pietjebelkees** [comment] 2018-03-08 17:44
Hey man,

thanks for attempting to help me, but it wasn't about the fork. I've
sent bch to my btc wallet and normally I go to settings -> bitcoin cash
-> duplicate and then it creates a bch wallet with the bch in it.

transaction confirmed and my copay wallet shows the exact amount of bch
when I click on duplicate but it doesn't show up in the wallet.

i already installed it on 2 other devices with recovery seed, scanned my
bch and btc wallets, tried the recovery tool. Nothing works.

yes I agree copay is secure, but because of a bug i lost 40% of my
savings, that's why I'm so mad. And support isn't helping me at all.

sorry for the late response, I was on a bussiness trip.

Riley Alexander schreef op 2018-02-26 16:41: 

> pietjebelkees,
> I am not copay support, HOWEVER, I will attempt to help you, as I was able to resolve the issue I had. It had to do with needing to make sure I have the LATEST version of copay installed, and then re-importing the 12 phrase backup seeds. Once re-imported, the multisig bch opened up with no problems at all. 
> 
> It sounds to me like you might be having another issue/bug. Are you positive that you had that BTC balance in the wallet during the July fork? Or did you recently put the funds into that wallet? It could be a bug simply where it is saying you have BCH by mistake when you really dont. 
> 
> And for the record, I would not be bashing copay. Copay is actually one of the most secure mobile wallets that I have ever used, and I have been in the bitcoin space over 5 years. It is the only multisig wallet that I trust with funds. 
> 
> Also, for the record: Copay Wallet = Bitpay Wallet = Bitcoin.com Wallet. They all use more or less the exact same source code with just minor modifications, but it all was written by Copay Dev's (funded by Bitpay) 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://webmail.countermail.com/redirto.php?&amp;url=https%3A%2F%2Fgithub.com%2Fbitpay%2Fcopay%2Fissues%2F7556%23issuecomment-368544467
[2]
https://webmail.countermail.com/redirto.php?&amp;url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAjFnAd0AW4X7xq1t-CjVvESI1j3-ZxXxks5tYtCigaJpZM4RHu2j

**Comment by BGalliotti** [comment] 2018-04-23 19:38
Hello,
We apologize for the long delay in follow up. Bitcoin grew a lot in 2017. This resulted in doubling the number of support inquiries we get, so it has taken much longer to get back to you. We have hired additional staff and made improvements to our support process to be more effective.
We are re-arranging our tickets in order to improve our service.


**Please update your BitPay wallet app to the latest version, and let us know if you have any more issues.**


If you are using the BitPay wallet on your mobile device, please update the wallet application in the [App Store (iOS)](https://itunes.apple.com/us/app/bitpay-secure-bitcoin-wallet/id1149581638) or [Google Play Store (Android)](https://play.google.com/store/apps/details?id=com.bitpay.wallet). If you are using the wallet on a desktop computer, you can download the most recent version of the BitPay wallet [here](https://bitpay.com/wallet).

Since this thread did not have any responses in a while we will be closing it.
**Please if you still need support, open a new one, we will be happy to help you.**


Thanks.

**Closed by BGalliotti** 2018-04-23 19:38 UTC
