### ISSUE TITLE
Can't create wallet on iOS 10

### ISSUE THREAD

**Issue by ffxsam** [bitpay/copay#4649] opened 2016-08-05 06:05 UTC
The following error occurs when I load the app for the first time and try to create a new wallet.![](http://i.imgur.com/9QSaj7s.jpg)

**Comment by dabura667** [comment] 2016-08-05 10:18
Assertion Error, chainCode was 64 bytes long!!! O_o!!

Scary to think what a bug like that would do if it wasn't caught and tried to make your wallet anyways...

iOS10 is currently not supported afaik. :-(

Thanks for the report!

**Comment by ffxsam** [comment] 2016-08-05 14:15
Yeah, I'm reporting it ahead of the iOS 10 release so the developers can fix it.

**Comment by gabegattis** [comment] 2016-08-05 18:14
Yeah, invalid chain code length is pretty worrisome. We should definitely investigate this. Hopefully there is not a bug in bitcore-lib.

**Comment by matiu** [comment] 2016-08-09 15:08
closing this one. Dup: https://github.com/bitpay/copay/issues/4570

**Closed by matiu** 2016-08-09 15:08 UTC
