### ISSUE TITLE
On notifications, show which wallet received funds

### ISSUE THREAD

**Issue by eleuteromaniaco** [bitpay/copay#4191] opened 2016-05-05 22:53 UTC
When having many Copay wallets and having new funds notifications, one needs to check for each wallet to find which of them was the notification for.

Showing the name of the wallet in the notification would easily solve the problem.

Example:
![copay notification](https://cloud.githubusercontent.com/assets/8605599/15059775/79a07034-12fb-11e6-9496-b3a8e84a0110.png)

**Comment by matiu** [comment] 2016-05-06 12:10
Newer versions of Copay / BWS encrypt wallet names and copayer names so BWS do not know that information.

Push notification are send by BWS so that information is not available any more (old push use to show the Wallet Name).

Maybe we can do that optional so users can decide whether or not to encrypt their wallet name? Other option will be to add color or similar to the notification.

Finally, note that taping on the notification will take you to the right wallet. The notification has a hash of the walletId.

Closing this issue since this is the intended behavior, but please let us know that you think about the above ideas.

**Closed by matiu** 2016-05-06 12:10 UTC

**Comment by eleuteromaniaco** [comment] 2016-05-07 03:04
An option to make that optional is too specific to exist I believe, and is nice to know that BWS does not know my wallet name. So I guess is fine like it is now.

Maybe sharing wallet's color with BWS could help, and showing a bullet or something in the notification with the color used in the wallet. It would in my case where each wallet has its own color and I remember which color they are.

Thanks.

**Comment by matiu** [comment] 2016-05-07 07:46
@eleuteromaniaco Thanks a lot for your valuable input!
