### ISSUE TITLE
[Android] White screen after Copay splash screen

### ISSUE THREAD

**Issue by ddepra** [bitpay/copay#3355] opened 2015-10-28 19:52 UTC
On Android 4.2.2, at startup, after the Copay splash screen, the screen stays white.

I first installed it Sunday 25/10 and then, after some day of usage (five wallets, some transactions, ...), it started doing that on Tuesday 27/10.

I already tried to uninstall and install it again. It worked only one time just after the reinstallation and then, the problem was back.

**Comment by matiu** [comment] 2015-10-29 12:43
Thanks for the report, we are sorry you are having inconveniences with Copay.

Copay encrypts the wallet data using the device ID, provided by the operating system. JIC, Is there anything special regarding that in your device? Are you using external storage (like a memory card)?

The upcoming version (1.5) will provide more feedback to the user if there is a decryption related error (as modified by https://github.com/bitpay/copay/pull/3354 ).

**Comment by ddepra** [comment] 2015-10-29 13:27
Indeed, my device has an external storage (memory card).

As soon as the new version is available, I'll install it and provide you the feedback provided by the app.

**Comment by ddepra** [comment] 2015-10-29 22:18
Indeed, the app report the following:

"Could not decrypt storage: device ID mismatch".

Any suggestion of what I can do ? Wait for a fix ? Try reinstalling it again ?

**Comment by matiu** [comment] 2015-10-29 22:33
Just in case, did you change the memory card from one device to other?

We will try to reproduce the problem using an Android device with external storage before recommending a work around.

**Comment by ddepra** [comment] 2015-10-29 22:47
This memory card has been in the device for 1 or 2 years now.

**Comment by matiu** [comment] 2015-10-30 13:46
According to our code (see https://github.com/bitpay/copay/blob/master/cordova/config.xml#L15)
Copay should never be installed on external storage (like SD cards on Android Devices). We have tried to reproduce your issue, but the option "Move to SD Card" on Android Application Manager is (correctly) disabled (using Android 4.4.2).

In your case, Is the option enabled? How you managed to install Copay in the external storage?

Could you try to install it on internal storage and check if it works correctly?

Thanks a lot for your patience and collaboration.

**Comment by ddepra** [comment] 2015-10-30 16:58
The option "Move to SD Card" is well disabled also. Copay was not installed on my SD Card.

I've just pushed the "Clear Data" button and relaunch Copay. It starts just like after a reinstall and I'll restore my backup. I'll keep you posted if the problem occurs again.

**Comment by XBTdev** [comment] 2015-11-02 07:25
My friend had the same issue #3173 and we didn't ever figure it out. My friend has since passed away from lung cancer, and he only had 0.2 btc in his wallet which I had given him. He couldn't remember his password before he passed away, but I guess you can't take it with you anyhow.

**Comment by matiu** [comment] 2015-11-12 11:13
This  is fixed in 1.5. In case there is a critical error, a message is shown. We also removed the UUID encryption that seems to cause problems in some android devices.

**Closed** 2015-11-12 11:13 UTC
