### ISSUE TITLE
Transaction doesn't appear in blockchain

### ISSUE THREAD

**Issue by 0blivio** [bitpay/copay#4394] opened 2016-06-15 05:00 UTC
Hi, i sent coins to an address and this address didn't receive the coins. I checked the Tx id and it says it doesn't exist... My coins are gone and i don't know what to do

**Comment by dabura667** [comment] 2016-06-15 08:07
Is there a pending proposal on your main wallet screen?

**Comment by JDonadio** [comment] 2016-06-15 12:23
Something like this

![image](https://cloud.githubusercontent.com/assets/13851807/16079600/b9ce35de-32da-11e6-8172-628832d3ba13.png)

**Comment by 0blivio** [comment] 2016-06-15 14:32
![senza_titolo](https://cloud.githubusercontent.com/assets/19850967/16083661/d2118cc8-32e3-11e6-92b2-de726bb7309d.jpg)

Every time i open copay, it shows me "A few seconds ago".
THis is the TX id of the 3rd transaction (+0.016078) d1c645c39986d65a56a524f6c6d7e4380ff711d994d71635d0f2060ec3c0d29a

2nd Transaction 9b5fae5f3e17f6a713e4df766d3e21b31f0de3932ffc6fc86196b75f45b6cb7b (+0.013244)

1st transaction 0e0f38b43cd839ac98f4bd06c0bd78f685e7dad941e411f70454c7b668344c7f (-0.029147)

Now my balance is 0 and lost 18€

**Comment by matiu** [comment] 2016-06-15 14:46
Let us investigate this issue with the information you sent, and we will get back to you.

In the last transaction (0e0f38b43cd839ac98f4bd06c0bd78f685e7dad941e411f70454c7b668344c7f) when you click on 'see it on the blockchain', what it shows? Can you share a screenshot there?

**Comment by 0blivio** [comment] 2016-06-15 14:49
I tried checking Tx with BLockchain.info and it simply show unconfirmed transactions. I will wait 24 hours

**Comment by matiu** [comment] 2016-06-15 14:51
Please note that inputs of your outgoing transaction:
(this one for example):
https://insight.bitpay.com/tx/d1c645c39986d65a56a524f6c6d7e4380ff711d994d71635d0f2060ec3c0d29a

are not yet confirmed, and has a low feeg (this is not related to Copay, but the one that sent you the original funds). So until that inputs are confirmed, your Copay transaction cannot be confirmed either.

**Comment by braydonf** [comment] 2016-06-15 15:08
Also, it looks like the transactions are depending/spending on a long chain of unconfirmed transactions/outputs.

**Comment by dabura667** [comment] 2016-06-15 15:50
> Now my balance is 0 and lost 18€

You did not lose money. The money was never technically yours.

In bitcoin, money is only considered "yours" if it is actually confirmed in the blockchain.

Now, most of the time when someone sends you bitcoin, wallets TELL you "this is your bitcoin" and let you spend it to other people under the assumption that "oh, well all bitcoin transactions should eventually confirm in the blockchain, so rather than making the user wait 10 minutes for every transaction, let them pass bitcoin along before confirming"

looking at your wallet, I see this flow of bitcoin:

1. Someone sent to your address 1EVemUnD7RdjS52U2msSTpSBzyFoqR9kYW
2. Someone sent to your address 1MWTddPgzfdu3iahvnmgaUn3uVfjrD6kgv
3. You sent to 1EGkuXH2TeVD3zccYDomNkSwvPUz72Qwt5

the transactions sending to 1 and 2 are 335 bytes with a 0.0001 BTC fee attached... this works out to about 29 satoshis per byte of fee.

https://bitcoinfees.21.co/

On this site, it shows that 29 satoshis per byte is VERY CROWDED. and will take a very long time to clear. You need at least 80 satoshis per byte to get confirmed in the next block or so...

And to make matters worse, the people who sent you the bitcoins look like they are some sort of automated thing (a program of some sort) that was programmed to ALWAYS USE 0.0001 BTC fee... (which is bad, because the necessary fee changes all the time... setting a static fee is bad.)

So, this can turn out one of three ways:

1. There are more than 20 transactions that are chained together un-confirmed before sending to you. If any one of those gets dropped from the network, then it will be as if they were never sent to you. This is not the fault of Copay, it is the fault of topmine.io. **Please contact topmine.io and ask support to re-send with a HIGHER FEE so it will actually confirm.** (You can see they have stopped withdrawals: https://twitter.com/topmine_btc/status/742990047847272449 )
2. If they all confirm, then your transaction will confirm too, and the money you sent will arrive at the address you sent it to. (If it was a payment address for a product, **please contact their support to return the bitcoin to you**)

Right now, Copay is showing you the truth, if you view 0 confirmation transactions as good for payment.It sounds like the person you paid did not like 0 confirmation payments, and topmine.io created a situation where it is difficult to confirm...

@matiu Even if "child pays for parent" was implemented in the future, this person would have had to pay to make up for tons of transactions for the (vendor?) company that sent him the coins...

The assumption of 0 confirmation as good as gold is confusing to new users, and especially with current network congestion... the UI around this should need some improvement...

**Comment by isocolsky** [comment] 2016-06-29 18:04
@dabura667 I agree! There is some effort going on right now trying to improve this area of Copay.

Closing this one as all txs are now confirmed.

**Closed by isocolsky** 2016-06-29 18:04 UTC
Labels: Support Request

**Comment by derekmahar** [comment] 2017-09-06 18:41
Does Bitpay Wallet Service and Copay discard transactions that the Bitcoin network never confirms and deletes from the mempool?  How long does this typically take?

**Comment by gangbru** [comment] 2018-11-20 13:39
Bitpay and Copay both sites are unconfirmed from location. That is not case, how you introduce to users. There pools are vanished from. So, there's no mining-no TX-no confirmation to fly to wallets. That is no configured for transactions!
