### ISSUE TITLE
Add transaction history item for "Transfers"

### ISSUE THREAD

**Issue by JDonadio** [bitpay/copay#4858] opened 2016-10-25 15:59 UTC
_From @bitjson on October 19, 2016 0:56_

Current Copay:
![screen shot 2016-10-18 at 8 54 52 pm](https://cloud.githubusercontent.com/assets/904007/19501658/43ae3c98-9575-11e6-8d2d-97db38214183.png)

BitPay (right now):
![screen shot 2016-10-18 at 8 54 57 pm](https://cloud.githubusercontent.com/assets/904007/19501660/45748582-9575-11e6-8d64-c7f2104ef433.png)

_Copied from original issue: bitpay/bitpay-wallet#576_

**Comment by JDonadio** [comment] 2016-10-25 15:59
_From @bitjson on October 19, 2016 0:57_

The "moved" items always use the "Sent" icon

**Comment by matiu** [comment] 2016-10-26 11:58
"moved" refers to moved inside the same wallet. While displaying movements between different wallets of the same user would be desirable, it is a new feature.

**Comment by bitjson** [comment] 2016-10-27 21:46
@matiu – oh, didn't realize that. How do you do that? The user manually sends money from the wallet to an address copied from the receive tab?

**Comment by matiu** [comment] 2016-10-27 22:39
yes

**Comment by bitjson** [comment] 2016-10-28 00:45
Not a bug – moving to: https://github.com/bitpay/copay/issues/4937

**Closed by bitjson** 2016-10-28 00:45 UTC
Labels: Design Needed, Feature Request
