### ISSUE TITLE
Private key and 12 word mnemonic left sitting in clear text in logfile on disk

### ISSUE THREAD

**Issue by jidanni** [bitpay/copay#7795] opened 2018-01-10 02:37 UTC
Please see https://github.com/Bitcoin-com/Wallet/issues/47 which also affects copay.

**Comment by travoc** [comment] 2018-01-21 19:12
I also discovered this issue on 12/26/18 and had a friend report this directly to Bitpay on that same day. It does not appear to be resolved. 

On Copay for Windows (and possibly others) wallet seeds are stored locally in plain text when wallets are created using the "Specific Recovery Phrase" feature. This issue mitigates any protection added by using the "Spending Password" key encryption feature and stores the secret recovery phrase in a location where a user may not expect, making it difficult for users to secure their Copay wallets.

After creating a Copay wallet from a recovery seed, plain text copies of recovered seed phrases can be found in a path similar to C:\Users\[username]\AppData\Local\copay\User Data\Default\Local App Settings\fmfiokedac...cbnmgbko\000003.log.

Additionally, creating a wallet with an extended seed password will cause the Chrome browser to store the plain text seed and encrypted password in the C:\Users\[username]\AppData\Local\copay\User Data\Default\Login Data file. The seed is displayed back to the user during a backup test due to Chrome's username/password saving features.

I suspect that it's related to the default Chromium configuration that is distributed with the Windows and Linux versions of Copay.

**Comment by jidanni** [comment] 2018-01-21 22:36
Once this hits the media things will go bonkers.

**Comment by matiu** [comment] 2018-01-22 14:23
Thanks a lot for the report (specially @travoc !). 

The issue is related to the journaling file of Chromium, used be NW.JS and Copay desktop versions. Last changes are stored there temporarily as a way to restore the data in case of a crash, I think we can fix this using https://github.com/nwjs/nw.js/wiki/save-persistent-data-in-app (Saving a plain text file directly to disk, instead of ChromeStorage). But since we are migrating to Electron https://electronjs.org/ we will check this issue in the next version, and obsolete the current one.

We will update this issue if we figure a way to disable the Chrome data log's or when the new version is released.

**Comment by matiu** [comment] 2019-02-20 16:54
This is fixed by:
1. The wallet now asks the encrypting password BEFORE storing the wallet, so the wallet's seed never gets into the storage unencrypted.
2. We have migrated to electrum, we no longer use Chrome Apps with maintains a log/journal of the storage.

**Closed by matiu** 2019-02-20 16:54 UTC
Labels: Feature Request
