### ISSUE TITLE
Strange error on a BIP72/73 URL

### ISSUE THREAD

**Issue by tonygallippi** [bitpay/copay#3037] opened 2015-07-24 16:50 UTC
When pasting this BIP72 URL into the address field of the Send form

bitcoin:1FGnRuNSVSMwJFVvdUVxTAwcVMcmFP4fL?amount=0.010000&r=https://bitpay.com/invoice?id=3RopChVe4xic3xn3r37Czg

(The bitpay invoice may be expired)

we get this error on Android and on iOS

If the invoice is expired, we should show an error that makes sense (This Payment Request has expired) or (This Payment Request is no longer valid)

![screenshot_2015-07-24-18-30-20](https://cloud.githubusercontent.com/assets/7226673/8879878/8187aba8-3202-11e5-9444-d1d6b036fc95.png)

**Comment by cjr-roland** [comment] 2015-07-24 17:02
This is a screenshot from my phone.
- On Android, copy pasting a BIP73 URL does not work, doesn't matter is the invoice is new or expired. I get the error message above.
- In case of the BIP72 URL it works until the invoice pass the 45 min grace period after expiration. Then I get the same error message.

**Comment by matiu** [comment] 2016-06-09 01:22
This should be fixed now.

Regarding the BIP73 URL, we checked the problem is on the merchant side.

**Closed by matiu** 2016-06-09 01:22 UTC
