### ISSUE TITLE
Not confirmed

### ISSUE THREAD

**Issue by patriots1121** [bitpay/copay#8932] opened 2018-07-31 15:24 UTC
My transaction still isn’t confirmed

**Comment by BGalliotti** [comment] 2018-07-31 15:55
Hello @patriots1121 

Thanks for reaching out to us.

**If you need answers on your previous inquiry please create a comment on the latest thread.**
You have not provided us any additional information so we can investigate.

Have you read #8803  ?

There are two options: 

- The transaction is not confirmed due to very low fees (and is not very likely to be ever confirmed..)
- The transaction is a double spend attempt. In this case, the transaction attempts to use funds that are already spent, reason why it will never be confirmed.

We are closing this thread.
Kind regards.

**Closed by BGalliotti** 2018-07-31 15:55 UTC
