### ISSUE TITLE
Nexus 6p camera crashing constantly when i use copay

### ISSUE THREAD

**Issue by kitsboy** [bitpay/copay#4249] opened 2016-05-25 06:25 UTC
...and I think when i try to scan a QR code, it crashes and try's to start google translate in the background....then it stops also after a second.

Any suggestions on how to stop this?

**Comment by matiu** [comment] 2016-05-30 13:02
we are not able to reproduce this issue, tried on one Nexus 6p/5x and 5. What Copay version are you using? Android 6.0.1?

**Comment by kitsboy** [comment] 2016-06-02 01:50
Copay version: 1.12.14
Android : 6.0.1

Everytime I try to send BTC, and the camera opens, I scan the QR code...it
crashes, and says: Unfortunately, Copay has stopped. and asks if I want to
: "Send report" or "ok"

I am not sure if there is a conflict with another APP that I may
downloaded. A few times the "Google Translate" APP opens when Copay crashes.

I appreciate you looking at this issue, thank you for your time.

kindest,
Cam


On Mon, May 30, 2016 at 6:02 AM, Matias Alejo Garcia <
notifications@github.com> wrote:

> we are not able to reproduce this issue, tried on one Nexus 6p/5x and 5.
> What Copay version are you using? Android 6.0.1?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitpay/copay/issues/4249#issuecomment-222488203>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABlHYgvPvZCVV1WDDr4wZ86Mc3VXe19qks5qGt_3gaJpZM4ImM2i>
> .
>



-- 


[image: --]

Cameron Taylor
[image: https://]about.me/cameron.taylor
<https://about.me/cameron.taylor?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by kitsboy** [comment] 2016-06-08 03:21
Is there any way I can trouble shoot this problem? Its preventing me from using Co-Pay.

**Comment by matiu** [comment] 2016-06-08 11:44
Hi,

We see only 3 crash reports in the Android app in the last months, and all
seems to be related to this issue and yourself:

The 3 crash are from:
Device: Nexus 6P (angler)
Android version:
Android 6.0
App version : 1048


Attached bellow the stacktrace.

Is your device is rooted? Can you try to uninstall the competing camera
app? (you mention Google Translate).


```
java.lang.RuntimeException: Unable to resume activity
{com.bitpay.copay/com.bitpay.copay.MainActivity}:
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null,
request=195543262, result=-1, data=Intent {
act=com.google.zxing.client.android.SCAN flg=0x80000 (has extras) }} to
activity {com.bitpay.copay/com.bitpay.copay.MainActivity}:
java.lang.NullPointerException: Attempt to invoke virtual method 'void
org.apache.cordova.CallbackContext.success(org.json.JSONObject)' on a null
object reference
at
android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5422)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.RuntimeException: Failure delivering result
ResultInfo{who=null, request=195543262, result=-1, data=Intent {
act=com.google.zxing.client.android.SCAN flg=0x80000 (has extras) }} to
activity {com.bitpay.copay/com.bitpay.copay.MainActivity}:
java.lang.NullPointerException: Attempt to invoke virtual method 'void
org.apache.cordova.CallbackContext.success(org.json.JSONObject)' on a null
object reference
at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
at
android.app.ActivityThread.performResumeActivity(ActivityThread.java:3089)
... 10 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method
'void org.apache.cordova.CallbackContext.success(org.json.JSONObject)' on a
null object reference
at com.phonegap.plugins.barcodescanner.BarcodeScanner.onActivityResult
(BarcodeScanner.java:193)
at
org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:151)
at
org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:348)
at android.app.Activity.dispatchActivityResult(Activity.java:6456)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
... 11 more
```

On Wed, Jun 8, 2016 at 12:21 AM, Cam <notifications@github.com> wrote:

> Is there any way I can trouble shoot this problem? Its preventing me from
> using Co-Pay.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitpay/copay/issues/4249#issuecomment-224477385>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAGCHK-YN5bpSaeLfiHfAP7abaGUEcd9ks5qJjVJgaJpZM4ImM2i>
> .
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by kitsboy** [comment] 2016-06-08 15:14
WOW, you can see my crash reports? I stopped sending them as I thought no
one ever saw them. I removed the one app I thought was the
problem....google translate, and rest cache...but its still happening. I
will send more crash reports now that i know.

No, my camera is NOT rooted...and when you suggest i remove the other
camera app, do you mean the google "stock" camera app?

Im so frustrated, as I really enjoy co-pay, but now I cant use it.

Thanks for all your help, please let me know what else I can do to figure
this out.

Cam

On Wed, Jun 8, 2016 at 4:44 AM, Matias Alejo Garcia <
notifications@github.com> wrote:

> Hi,
>
> We see only 3 crash reports in the Android app in the last months, and all
> seems to be related to this issue and yourself:
>
> The 3 crash are from:
> Device: Nexus 6P (angler)
> Android version:
> Android 6.0
> App version : 1048
>
>
> Attached bellow the stacktrace.
>
> Is your device is rooted? Can you try to uninstall the competing camera
> app? (you mention Google Translate).
>
>
> ```
> java.lang.RuntimeException: Unable to resume activity
> {com.bitpay.copay/com.bitpay.copay.MainActivity}:
> java.lang.RuntimeException: Failure delivering result ResultInfo{who=null,
> request=195543262, result=-1, data=Intent {
> act=com.google.zxing.client.android.SCAN flg=0x80000 (has extras) }} to
> activity {com.bitpay.copay/com.bitpay.copay.MainActivity}:
> java.lang.NullPointerException: Attempt to invoke virtual method 'void
> org.apache.cordova.CallbackContext.success(org.json.JSONObject)' on a null
> object reference
> at
> android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
> at
> android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
> at
> android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
> at android.app.ActivityThread.-wrap11(ActivityThread.java)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:148)
> at android.app.ActivityThread.main(ActivityThread.java:5422)
> at java.lang.reflect.Method.invoke(Native Method)
> at
>
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
> Caused by: java.lang.RuntimeException: Failure delivering result
> ResultInfo{who=null, request=195543262, result=-1, data=Intent {
> act=com.google.zxing.client.android.SCAN flg=0x80000 (has extras) }} to
> activity {com.bitpay.copay/com.bitpay.copay.MainActivity}:
> java.lang.NullPointerException: Attempt to invoke virtual method 'void
> org.apache.cordova.CallbackContext.success(org.json.JSONObject)' on a null
> object reference
> at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
> at
> android.app.ActivityThread.performResumeActivity(ActivityThread.java:3089)
> ... 10 more
> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method
> 'void org.apache.cordova.CallbackContext.success(org.json.JSONObject)' on a
> null object reference
> at com.phonegap.plugins.barcodescanner.BarcodeScanner.onActivityResult
> (BarcodeScanner.java:193)
> at
>
> org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:151)
> at
>
> org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:348)
> at android.app.Activity.dispatchActivityResult(Activity.java:6456)
> at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
> ... 11 more
> ```
>
> On Wed, Jun 8, 2016 at 12:21 AM, Cam <notifications@github.com> wrote:
>
> > Is there any way I can trouble shoot this problem? Its preventing me from
> > using Co-Pay.
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/bitpay/copay/issues/4249#issuecomment-224477385>,
> or mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AAGCHK-YN5bpSaeLfiHfAP7abaGUEcd9ks5qJjVJgaJpZM4ImM2i
> >
> > .
> >
>
>
>
> --
> Matías Alejo Garcia
> @ematiu
> Roads? Where we're going, we don't need roads!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitpay/copay/issues/4249#issuecomment-224565342>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABlHYtFu7minz_eTgLuxmJ7EGBEzDarFks5qJqskgaJpZM4ImM2i>
> .
>



-- 


[image: --]

Cameron Taylor
[image: https://]about.me/cameron.taylor
<https://about.me/cameron.taylor?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by JDonadio** [comment] 2016-12-07 18:58
@kitsboy it's fixed with the latest version? Please, you can try also the [BitPay distribution](https://bitpay.com/wallet). If the problem remains reopen the issue.

**Closed by JDonadio** 2016-12-07 18:58 UTC
Labels: Bug

**Comment by kitsboy** [comment] 2016-12-07 19:49
Thanks for your help! I reset my phone about 2 weeks ago, and reinstalled, seemed to fix it. I hope it was not maleware on my side:)

**Comment by JDonadio** [comment] 2016-12-07 20:01
Glad to read it!
