### ISSUE TITLE
BTC not received

### ISSUE THREAD

**Issue by drejkir** [bitpay/copay#4893] opened 2016-10-26 12:21 UTC
Hello!

I've sent btc to this wallet and I've not received it:
copay wallet:
1ArgAXzJixz3Bq7FKBNcs57vpoS3VNyWW5

**Comment by bitjson** [comment] 2016-10-26 15:23
Hey @drejkir – thanks for the report!

It looks like your transaction has not been confirmed yet by the bitcoin network: https://insight.bitpay.com/tx/12ef22dc1df214dfc49036340580f0d4a068cb8aa7413d65b569f581d505c531. Once it's confirmed, it will be available to spend from your wallet.

We're aware that this is not as clear as it could be in the user interface – you can watch development for the issue here: https://github.com/bitpay/copay/issues/4881.

(I'll close this individual issue since we're already working on it there.)

**Closed by bitjson** 2016-10-26 15:23 UTC
