### ISSUE TITLE
My Contacts not saving

### ISSUE THREAD

**Issue by JulianTosh** [bitpay/copay#4093] opened 2016-04-18 18:39 UTC
CoPay v1.9.4
Platform: Android 6.0.1, build MMB29V
Kernel: 3.10.40-g9a3e9ef
Hardware: Nexus 6

When I attempt to add an entry to "My Contacts", nothing gets saved.

Actions to reproduce:

1.  Open wallet account
2. Press 'Send'.
3. Press 'folder icon' in 'To' field.
4. Press 'My Contacts' tab.
5. Press '+ Add a new entry'
6. Press the 'scan' icon. Address fills field and green checkmark lights indicating a valid address.
7. Type in a label. Save button enabled.
8. Press 'Save' button.
9. My Contacts tab is displayed but empty of any addresses/labels with nothing to select.

Expected result: Bitcoin address/label displayed as a selectable object.

This functionality works fine on Chrome and another android tablet (galaxy tab 4).

**Comment by matiu** [comment] 2016-04-18 18:42
Can you check the sessions logs to see if there is any error reported?

Global preferences on the Side Menu -> About Copay -> session logs

On Mon, Apr 18, 2016 at 3:39 PM, JulianTosh <notifications@github.com>
wrote:

> CoPay v1.9.4
> Platform: Android 6.0.1, build MMB29V
> Kernel: 3.10.40-g9a3e9ef
> Hardware: Nexus 6
>
> When I attempt to add an entry to "My Contacts", nothing gets saved.
>
> Actions to reproduce:
>
>    1. Open wallet account
>    2. Press 'Send'.
>    3. Press 'folder icon' in 'To' field.
>    4. Press 'My Contacts' tab.
>    5. Press '+ Add a new entry'
>    6. Press the 'scan' icon. Address fills field and green checkmark
>    lights indicating a valid address.
>    7. Type in a label. Save button enabled.
>    8. Press 'Save' button.
>    9. My Contacts tab is displayed but empty of any addresses/labels with
>    nothing to select.
>
> Expected result: Bitcoin address/label displayed as a selectable object.
>
> This functionality works fine on Chrome and another android tablet (galaxy
> tab 4).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/4093>
>



-- 
BitPay.com

**Comment by JulianTosh** [comment] 2016-04-18 19:06
```
Binding touchstart elements...
Route change from: walletHome  to: preferencesGlobal
Route change from: walletHome  to: preferencesGlobal
Route change from: preferencesGlobal  to: about
Route change from: preferencesGlobal  to: about
Route change from: about  to: logs
Route change from: about  to: logs
Route change from: logs  to: about
Route change from: logs  to: about
Route change from: about  to: preferencesGlobal
Route change from: about  to: preferencesGlobal
Route change from: preferencesGlobal  to: walletHome
Route change from: preferencesGlobal  to: walletHome
Binding touchstart elements...
Writing: addressbook-livenet []
Route change from: walletHome  to: preferencesGlobal
Route change from: walletHome  to: preferencesGlobal
Route change from: preferencesGlobal  to: about
Route change from: preferencesGlobal  to: about
Route change from: about  to: logs
Route change from: about  to: logs
```

**Comment by JulianTosh** [comment] 2016-04-20 23:23
Now running 1.10.2 and My Contact still not functioning.

Session log:
```
txHistory saved.
Writing: addressbook-livenet[]
Route change from: walletHome to: preferencesGlobal
```

**Comment by cmgustavo** [comment] 2016-04-21 00:14
It works for me. But I have another issue that I don't know if it 's the same:

1) Create a new entry in address book (enter address and label)
2) Click Save
3) Select the new entry (closing address book and return to Send)
4) Cancel Send
5) Open address book again
6) The list of contacts appears empty
7) Change tab to "My Wallets" and then return to "My Contacts".
8) Last contact added now appears on the list

I have a Galaxy Tab (Android v4.4.2). We 'll prove it with Android 6.x

Thanks.

**Comment by gabrielbazan7** [comment] 2016-04-21 15:16
The PR fix @cmgustavo issue only.

**Comment by JulianTosh** [comment] 2016-04-28 15:21
@Kirvx Can you attempt this on your android 6 device? Be interesting to know if this too is isolated to android 6 (like the camera permission issue was).

Thanks!

**Comment by Kirvx** [comment] 2016-04-28 15:36
@JulianTosh Works great on mine :/

**Comment by gabrielbazan7** [comment] 2016-05-02 13:25
Working fine on Nexus 5 ( Android 6.0.1). @JulianTosh you still have this issue ?

**Comment by JulianTosh** [comment] 2016-05-02 15:13
Yup. I'm on 1.12.1. Same problem. Checked the session log and there's only the 'Writing: addressbook-livenet" message that seems relevant. Anyway to get a more detailed log event for that action?

**Comment by matiu** [comment] 2016-06-09 02:28
Unluckily we are not able to reproduce the error, tried on several Android devices, and versions, and even your same device/android version. Please check if there is some problem with the device storage itself. I dont think we can provide more help.

**Closed by matiu** 2016-06-09 02:28 UTC
