### ISSUE TITLE
Why is Copay not on F-droid.org?

### ISSUE THREAD

**Issue by ole-tange** [bitpay/copay#4527] opened 2016-07-01 16:24 UTC
When looking for software for my phone I always prefer free (as in freedom) software. I was sorry to learn that Copay is not listed on F-droid, but happy to learn that it is indeed free software.

Since you clearly understand why security software needs to be free software, please consider publishing Copay on F-droid, too.

**Comment by martindale** [comment] 2016-07-01 22:25
Duplicate of #2465.

**Closed** 2016-07-03 17:58 UTC
