### ISSUE TITLE
Bad Request Issue

### ISSUE THREAD

**Issue by ghost** [bitpay/copay#5407] opened 2017-01-04 21:42 UTC
Hi,
I have a Bad Request Problem when sending from the Node Client...looks like the problem is that when the /signature request is send, the signatures array is empty

its the newest client but an older wallet (if that could be an issue)

**Comment by romancsandl** [comment] 2017-01-04 23:49
also tx_proposals call not working with {code: "TX_NOT_FOUND", message: "Transaction proposal not found"}

**Comment by romancsandl** [comment] 2017-01-05 00:50
could it be that the bitpay api has changed? i do not get a signatures property in the /publish call

**Comment by romancsandl** [comment] 2017-01-05 01:15
i found another issue #3991 which is the exact same but closed...but the issue is definitely still open...i could also not fix it with the suggestions in that issue

**Comment by matiu** [comment] 2017-01-12 12:42
Hi,

What you mean by "the node client"? What platform / copay version are you using?
Could you share exactly the error you are getting, and in response of which action?

**Comment by umagon** [comment] 2017-01-16 17:23
Are there any news for this issue?

**Comment by romancsandl** [comment] 2017-01-24 23:35
the web based client you can download...the error is in all apps i used (also the android version)
and i guess the error would be even in an ios client...because the app is not the problem, the server is...there is no response ..
"when sending there are signatures wanted from the bws server...but there are no signatures sent within the process...so the issue looks to be on bws side not the client"
at the /signatures call i get a {"code":"BAD_SIGNATURES","message":"Bad signatures"} response

**Comment by umagon** [comment] 2017-09-13 21:45
Did you ever get it working..?

**Comment by romancsandl** [comment] 2017-09-13 21:51
no...in my opinion they robbed the coins...either by accident or on purpose...you would need access to that proprietary api they are using to search through the tables to find a corresponding key or anything like that...without that i see no chance...i would be really surprised if anyone can solve this issue with the given code alone

**Comment by matiu** [comment] 2017-09-13 22:25
1. The api is not propietary
2. The private keys needed to move your coins never leave your device, and
are not stored server side.

**Comment by umagon** [comment] 2017-09-14 21:03
Can you check what I asked in my issue (#3991)? I would like to continue trying by my own, but I need my doubts to be evacuated.

Also, I would like it to be open, since that issue is nowhere near to be solved.

**Comment by umagon** [comment] 2017-09-18 18:58
@matiu You won't reply to me anymore in either issue?

**Comment by matiu** [comment] 2017-09-18 19:01
@umagon I had replied your issue on detail on https://github.com/bitpay/copay/issues/3991 I am afraid there is nothing else for me to add regarding that.

**Comment by matiu** [comment] 2017-09-18 19:02
@romancsandl there is no "the web based client you can download." Copay is not provided as web app.

**Comment by romancsandl** [comment] 2017-09-18 19:07
@matiu it is a nodejs app...you can run that anywhere where node is installed...it is clearly stated you can test the app in a browser in the readme.md

**Comment by umagon** [comment] 2017-09-18 19:20
@matiu The last thing you said about my issue was that perhaps the rom I was using corrupted the xpriv. I reinstalled the rom and tried to send btc to another wallet. I got a different error and sent you the pictures through gitter. I got no reply.

If you won't, can someone else in the team try to help me?

**Comment by matiu** [comment] 2017-09-18 19:26
@romancsandl you stated "no...in my opinion they robbed the coins...either by accident or on purpose." What you mean by that?  It order to move you coins the bitcoin private keys are necesary. Those never leave your device.  Running Copay on a web browser is only meant for developing, never for production/real coin use. Different plugins can access you localstorage and stole your bitcoin private keys.

**Comment by matiu** [comment] 2017-09-18 19:31
@umagon I hope you understand we can't support unoffical android images. Copay have more that 1 millon users, on 7 different platforms. I think we try very hard to help you with your problem, but it is impossible for us to know what a non official android version would do with the storage or libraries. You are welcomed to open a new ticket describing in detail your problem and maybe someone on our opensource comunity can help.

**Comment by romancsandl** [comment] 2017-09-18 19:38
i tried to figure out what the actual problem was by running it through a webbrowser...as far as i understand i could just login from another device as long as my pw and everything is correct or not? are there no new keys generated then? anyway...we tried from the actual phone where app was used without any progress nor real help from you...the original owner of the phone opened a bugreport which got closed unresolved and every once in a while you try to make people who are still not giving up their coins feel like it is their fault that they cannot access their coins...in my opinion this app should not be used by anyone at all...

**Comment by matiu** [comment] 2017-09-18 19:49
@romancsandl I am sorry you feel that way.    You can try our recovery tool at https://bitpay.github.io/copay-recovery/ to see of you see you BTC balance there, and try to move your coins from there.

**Comment by romancsandl** [comment] 2017-09-18 19:55
#3991 tried that numerous times...coins are in the wallet...sending them no another wallet is not possible
#4266 was the original issue ...closed without resolving...

**Comment by umagon** [comment] 2017-09-18 21:38
Did any "BAD_SIGNATURES" error get resolved? Have all those people created their wallets in custom roms of android?

Can we triangulate the error by comparing our different circumstances?

**Comment by romancsandl** [comment] 2017-09-18 21:41
as already stated in #3991 that there was no custom rom used...galaxy s6...original software

**Comment by umagon** [comment] 2017-09-19 18:04
I know, that's why I say it has nothing to do with my android rom. We have to see why we all have this problem.

**Comment by romancsandl** [comment] 2017-09-19 18:58
my guess is there was a bug with key generation or an api change...

**Comment by umagon** [comment] 2017-09-25 17:31
@romancsandl do you remember when did you create your wallet? In which OS? I'm thinking that maybe I did in windows 7 after all.

**Comment by romancsandl** [comment] 2017-09-25 19:26
the wallet was created on an samsung s6...android ...i just tried to get access/recover from a windows10...after we figured that it is not working on the s6...
look i get you want your coins back...we want them too...but as long as the copay guys don't seriously cooperate you just waste your time...

**Comment by umagon** [comment] 2017-09-26 15:40
What else can we do?

**Comment by gabrielbazan7** [comment] 2019-01-11 19:16
I will close this ticket since it's too old, please reopen if needed.

**Closed by gabrielbazan7** 2019-01-11 19:16 UTC
Labels: Support Request
