### ISSUE TITLE
Stuck on Loading screen with Copay/Trezor

### ISSUE THREAD

**Issue by wesdacar** [bitpay/copay#6957] opened 2017-10-23 08:14 UTC
Trying to make a 2-3 payment on Copay with Trezor. Once the transaction is entered, and I have clicked pay then the Trezor window opens and says loading.. but remains like that for hours. If I close this it show the created payment in the copay window (waiting for approval by other signatory). On the other signers window it shows the payment, if he accepts it (signs) then it also goes to loading for hours) - no result. We have tried a few times today and same thing happens... ?any suggestions?

**Comment by copayIsGreat** [comment] 2017-10-23 08:17
This is happening to me also.  Started 3 hours ago

**Comment by wesdacar** [comment] 2017-10-23 10:19
<img width="665" alt="screen shot 2017-10-23 at 14 18 19" src="https://user-images.githubusercontent.com/14962829/31884079-11707c22-b7fd-11e7-829e-48e74cbb504c.png">

**Comment by wesdacar** [comment] 2017-10-23 10:20
just stays like that.... anyone have any ideas or same problem?

**Comment by antoniobp** [comment] 2017-10-23 10:22
same issue ....

Uncaught (in promise) Error: Config too old; 1508715002 >= 1508601310
at o (https://connect.trezor.io/1/popup/popup-dist.js:1030:891)
at sendResponseAndClearCallback (extensions::messaging:417:9)
at messageListener (extensions::messaging:449:11)
at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:140:26)
at EventImpl.dispatch_ (extensions::event_bindings:387:35)
at EventImpl.dispatch (extensions::event_bindings:409:17)
at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:140:26)
at dispatchOnMessage (extensions::messaging:390:22)

**Comment by wesdacar** [comment] 2017-10-23 10:32
Can someone from Copay please respond, there are more people with same issue - would be great if someone would assist us ??

**Comment by lenh** [comment] 2017-10-23 10:33
Same issue here.
Unable to sign txns on multi-sig accounts...
Please advise.

**Comment by sserrano44** [comment] 2017-10-23 12:06
same here :-| 
It seems is an error checking a configuration that has a timestamp, if you move your clock before the timestamp it works

**Comment by Oodges** [comment] 2017-10-23 12:33
Having the same issue here.

**Comment by JDonadio** [comment] 2017-10-23 12:34
Hi there, did you try closing the trezor view and trying again?. If the trezor chrome-app wasn't initiated before the Copay request could be probably the cause.

**Comment by Jacobbubble** [comment] 2017-10-23 12:44
JDonadio, yes I've tried that. Seems to be a common issue.

**Comment by wesdacar** [comment] 2017-10-23 13:00
still problem

**Comment by johnvamo** [comment] 2017-10-23 13:54
Thanks for the update...same situation...urgent solutions needed.

**Comment by lenh** [comment] 2017-10-23 13:57
We solved our issue by installing our own instance of BWS - [https://github.com/bitpay/bitcore-wallet-service)](url)

**Comment by matiu** [comment] 2017-10-23 14:07
@lenh this issue is not related to BWS.

IT seems to be solved now. IT was on the Trezor API side:
https://github.com/trezor/connect/issues/84

Please try again.

**Closed by matiu** 2017-10-23 14:07 UTC

**Comment by johnvamo** [comment] 2017-10-23 14:18
Ok. Thanks...the transaction went through...se debe the proposal payment correctly now...

**Comment by johnvamo** [comment] 2017-10-23 22:17
Hi, we succeeded making one transaction...the other copayer send his transaction, was accepted successfully...and it is 6 hours after without any confirmation...is happening something... congestion? It was sent with a urgent fee...not so clear was is the subject now...thanks for the support.
