### ISSUE TITLE
Webcam light turns on briefly after opening macOS Bitpay app

### ISSUE THREAD

**Issue by zacharytamas** [bitpay/copay#5409] opened 2017-01-05 03:15 UTC
This happened three launches in a row. Also Bitpay never closes correctly when I Quit the app and I have to Force Quit it. This makes me very nervous as I can't see any reason Bitpay should need to turn my webcam on. Now worrying my wallet I added to it is compromised.

Downloaded from here: https://github.com/bitpay/copay/releases/tag/bitpay
This is on a 2016 MBP and macOS 10.12.2 (16C67)

**Comment by zacharytamas** [comment] 2017-01-05 03:43
After more thought I think this may be the QR code scanner portion initializing, perhaps?

**Comment by bitjson** [comment] 2017-01-05 04:43
Thanks for reporting @zacharytamas! It's working as designed, but I think it definitely needs review. (It's not uncommon for people to assume the camera quirks on desktop are due to malicious code.)

I was actually working on improving this today as part of a solution to #4935 and #4967. Hopefully I'll have something ready to PR soon. If it's ok with you, I'm going to close this issue in favor of those.

**Closed by bitjson** 2017-01-05 04:43 UTC

**Comment by bitjson** [comment] 2017-04-24 15:20
Just to update this issue – this was fixed here: https://github.com/bitpay/copay/pull/5440
